import type {
  ChemistryCategory,
  ChemistryLibraryItem,
  ChemistryModule,
  InorganicLibraryItem,
  OrganicLibraryItem,
  SidebarCategory,
} from "./types";

export const INORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "glassware", name: "Reaction vessel", hint: "Flasks, tubes, funnels and reaction containers" },
  { id: "equipment", name: "Assistive devices", hint: "Heat, support, measuring and setup tools" },
  { id: "solids", name: "Solid chemical", hint: "Powders, salts and metal samples" },
  { id: "liquids", name: "Liquid reagents", hint: "Acids, solvents and solutions" },
  { id: "gases", name: "Gases", hint: "Common gaseous reactants and products" },
];

export const ORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "atoms", name: "Atoms", hint: "Place atoms and hetero atoms" },
  { id: "bonds", name: "Bonds", hint: "Create single, double and triple bonds" },
  { id: "rings", name: "Ring templates", hint: "Drop common cyclic scaffolds" },
  { id: "groups", name: "Groups", hint: "Quick functional-group fragments" },
];

export const INORGANIC_LIBRARY: InorganicLibraryItem[] = [
  {
    id: "beaker-250",
    module: "inorganic",
    category: "glassware",
    name: "Beaker 250 mL",
    symbol: "BK",
    state: "glassware",
    accent: "#38bdf8",
    description: "General purpose mixing and heating vessel.",
  },
  {
    id: "erlenmeyer-250",
    module: "inorganic",
    category: "glassware",
    name: "Erlenmeyer Flask",
    symbol: "FL",
    state: "glassware",
    accent: "#818cf8",
    description: "Good for swirling and controlled reactions.",
  },
  {
    id: "test-tube",
    module: "inorganic",
    category: "glassware",
    name: "Large Test Tube",
    symbol: "TT",
    state: "glassware",
    accent: "#14b8a6",
    description: "Tall straight-wall test tube for heating and observation.",
  },
  {
    id: "test-tube-small",
    module: "inorganic",
    category: "glassware",
    name: "Small Test Tube",
    symbol: "TT",
    state: "glassware",
    accent: "#2dd4bf",
    description: "Compact tube for micro-scale reaction samples.",
  },
  {
    id: "glass-bottle",
    module: "inorganic",
    category: "glassware",
    name: "Glass Bottle",
    symbol: "BT",
    state: "glassware",
    accent: "#94a3b8",
    description: "General purpose bottle for collecting or storing reagents.",
  },
  {
    id: "sample-jar",
    module: "inorganic",
    category: "glassware",
    name: "Sample Jar",
    symbol: "JR",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Wide-mouth jar for powders, granules and preserved samples.",
  },
  {
    id: "funnel",
    module: "inorganic",
    category: "glassware",
    name: "Glass Funnel",
    symbol: "FN",
    state: "glassware",
    accent: "#f59e0b",
    description: "Useful for transfer and filtration setup.",
  },
  {
    id: "burner",
    module: "inorganic",
    category: "equipment",
    name: "Bunsen Burner",
    symbol: "HT",
    state: "device",
    accent: "#fb7185",
    description: "Heat source for combustion and thermal decomposition.",
  },
  {
    id: "tripod",
    module: "inorganic",
    category: "equipment",
    name: "Tripod Stand",
    symbol: "ST",
    state: "device",
    accent: "#64748b",
    description: "Stable support for vessels above a burner.",
  },
  {
    id: "thermometer",
    module: "inorganic",
    category: "equipment",
    name: "Thermometer",
    symbol: "TMP",
    state: "device",
    accent: "#22c55e",
    description: "Track reaction and solvent temperatures.",
  },
  {
    id: "balance",
    module: "inorganic",
    category: "equipment",
    name: "Digital Balance",
    symbol: "MS",
    state: "device",
    accent: "#a78bfa",
    description: "Mass measurement before combining reagents.",
  },
  {
    id: "nacl",
    module: "inorganic",
    category: "solids",
    name: "Sodium Chloride",
    symbol: "NaCl",
    formula: "NaCl",
    state: "solid",
    accent: "#f8fafc",
    description: "Neutral ionic salt for dissolution and precipitation work.",
  },
  {
    id: "cuso4",
    module: "inorganic",
    category: "solids",
    name: "Copper Sulfate",
    symbol: "CuSO4",
    formula: "CuSO4",
    state: "solid",
    accent: "#38bdf8",
    description: "Blue crystalline solid often used in displacement reactions.",
  },
  {
    id: "iron",
    module: "inorganic",
    category: "solids",
    name: "Iron Filings",
    symbol: "Fe",
    formula: "Fe",
    state: "solid",
    accent: "#94a3b8",
    description: "Metal reagent for replacement and magnetism demonstrations.",
  },
  {
    id: "sulfur",
    module: "inorganic",
    category: "solids",
    name: "Sulfur Powder",
    symbol: "S",
    formula: "S",
    state: "solid",
    accent: "#fde047",
    description: "Yellow non-metal commonly used in synthesis demonstrations.",
  },
  {
    id: "water",
    module: "inorganic",
    category: "liquids",
    name: "Distilled Water",
    symbol: "H2O",
    formula: "H2O",
    state: "liquid",
    accent: "#67e8f9",
    description: "Default solvent for dilution and washing.",
  },
  {
    id: "hcl",
    module: "inorganic",
    category: "liquids",
    name: "Hydrochloric Acid",
    symbol: "HCl",
    formula: "HCl",
    state: "liquid",
    accent: "#fb7185",
    description: "Strong acid for neutralization and gas evolution tests.",
  },
  {
    id: "naoh",
    module: "inorganic",
    category: "liquids",
    name: "Sodium Hydroxide",
    symbol: "NaOH",
    formula: "NaOH",
    state: "liquid",
    accent: "#22c55e",
    description: "Strong base for titration and precipitation setup.",
  },
  {
    id: "ethanol",
    module: "inorganic",
    category: "liquids",
    name: "Ethanol",
    symbol: "EtOH",
    formula: "C2H6O",
    state: "liquid",
    accent: "#f59e0b",
    description: "Volatile solvent for cleaning and miscibility tests.",
  },
  {
    id: "oxygen",
    module: "inorganic",
    category: "gases",
    name: "Oxygen",
    symbol: "O2",
    formula: "O2",
    state: "gas",
    accent: "#38bdf8",
    description: "Supports combustion and oxidation experiments.",
  },
  {
    id: "hydrogen",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen",
    symbol: "H2",
    formula: "H2",
    state: "gas",
    accent: "#f8fafc",
    description: "Light flammable gas for reduction demonstrations.",
  },
  {
    id: "co2",
    module: "inorganic",
    category: "gases",
    name: "Carbon Dioxide",
    symbol: "CO2",
    formula: "CO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Common acidic gas from carbonate reactions.",
  },
  {
    id: "chlorine",
    module: "inorganic",
    category: "gases",
    name: "Chlorine",
    symbol: "Cl2",
    formula: "Cl2",
    state: "gas",
    accent: "#a3e635",
    description: "Reactive halogen for displacement and bleaching examples.",
  },
];

export const ORGANIC_LIBRARY: OrganicLibraryItem[] = [
  {
    id: "atom-c",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "C",
    color: "#0f172a",
    description: "Carbon backbone atom.",
  },
  {
    id: "atom-h",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "H",
    color: "#e2e8f0",
    description: "Hydrogen atom.",
  },
  {
    id: "atom-o",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "O",
    color: "#ef4444",
    description: "Oxygen hetero atom.",
  },
  {
    id: "atom-n",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "N",
    color: "#3b82f6",
    description: "Nitrogen hetero atom.",
  },
  {
    id: "atom-cl",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Cl",
    color: "#22c55e",
    description: "Chloro substituent.",
  },
  {
    id: "atom-br",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Br",
    color: "#f97316",
    description: "Bromo substituent.",
  },
  {
    id: "bond-single",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Single",
    order: 1,
    color: "#475569",
    description: "Create or update a single bond.",
  },
  {
    id: "bond-double",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Double",
    order: 2,
    color: "#475569",
    description: "Create or update a double bond.",
  },
  {
    id: "bond-triple",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Triple",
    order: 3,
    color: "#475569",
    description: "Create or update a triple bond.",
  },
  {
    id: "bond-aromatic",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Aromatic",
    order: "aromatic",
    color: "#8b5cf6",
    description: "Use for aromatic link styling.",
  },
  {
    id: "ring-benzene",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Benzene",
    template: "benzene",
    color: "#ec4899",
    description: "Drop a six-member aromatic ring.",
  },
  {
    id: "ring-cyclohexane",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Cyclohexane",
    template: "cyclohexane",
    color: "#10b981",
    description: "Drop a six-member saturated ring.",
  },
  {
    id: "group-oh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "OH",
    color: "#ef4444",
    description: "Hydroxyl group fragment.",
  },
  {
    id: "group-cooh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "COOH",
    color: "#f97316",
    description: "Carboxylic acid fragment.",
  },
  {
    id: "group-nh2",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "NH2",
    color: "#3b82f6",
    description: "Primary amine fragment.",
  },
  {
    id: "group-ch3",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "CH3",
    color: "#0f172a",
    description: "Methyl fragment.",
  },
];

export function getCategoriesForModule(module: ChemistryModule): SidebarCategory[] {
  return module === "inorganic" ? INORGANIC_CATEGORIES : ORGANIC_CATEGORIES;
}

export function getLibraryForModule(module: ChemistryModule): ChemistryLibraryItem[] {
  return module === "inorganic" ? INORGANIC_LIBRARY : ORGANIC_LIBRARY;
}

export function getDefaultCategoryForModule(module: ChemistryModule): ChemistryCategory {
  return getCategoriesForModule(module)[0].id;
}
