import type {
  ChemistryCategory,
  ChemistryLibraryItem,
  ChemistryModule,
  InorganicLibraryItem,
  OrganicLibraryItem,
  SidebarCategory,
} from "./types";

export const INORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "glassware", name: "Reaction vessel", hint: "Flasks, tubes, funnels and reaction containers" },
  { id: "equipment", name: "Assistive devices", hint: "Heat, support, measuring and setup tools" },
  { id: "solids", name: "Solid chemical", hint: "Powders, salts and metal samples" },
  { id: "liquids", name: "Liquid reagents", hint: "Acids, solvents and solutions" },
  { id: "gases", name: "Gases", hint: "Common gaseous reactants and products" },
];

export const ORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "atoms", name: "Atoms", hint: "Place atoms and hetero atoms" },
  { id: "bonds", name: "Bonds", hint: "Create single, double and triple bonds" },
  { id: "rings", name: "Ring templates", hint: "Drop common cyclic scaffolds" },
  { id: "groups", name: "Groups", hint: "Quick functional-group fragments" },
];

export const INORGANIC_LIBRARY: InorganicLibraryItem[] = [
  {
    id: "round-bottom-flask",
    module: "inorganic",
    category: "glassware",
    name: "Round Bottomed Flask",
    symbol: "RF",
    state: "glassware",
    accent: "#7f8ea3",
    description: "Heat-resistant glass vessel for boiling and reaction setup.",
  },
  {
    id: "separatory-funnel",
    module: "inorganic",
    category: "glassware",
    name: "Globe Shaped Separatory Funnel",
    symbol: "SF",
    state: "glassware",
    accent: "#d5dde7",
    description: "Round stopcock funnel for separating liquid layers.",
  },
  {
    id: "gas-jar",
    module: "inorganic",
    category: "glassware",
    name: "Gas Jar",
    symbol: "GJ",
    state: "glassware",
    accent: "#d7dee8",
    description: "Wide cylindrical jar for collecting and observing gas.",
  },
  {
    id: "test-tube",
    module: "inorganic",
    category: "glassware",
    name: "Large Test Tube",
    symbol: "TT",
    state: "glassware",
    accent: "#14b8a6",
    description: "Tall straight-wall tube for small reactions and heating.",
  },
  {
    id: "burner",
    module: "inorganic",
    category: "equipment",
    name: "Alcohol Burner",
    symbol: "HT",
    state: "device",
    accent: "#fb7185",
    description: "Heat source for laboratory experiments.",
  },
  {
    id: "matchbox",
    module: "inorganic",
    category: "equipment",
    name: "Matchbox",
    symbol: "MBX",
    state: "device",
    accent: "#b44f50",
    description: "Matchbox with protruding matchstick for ignition demos.",
  },
  {
    id: "dropper",
    module: "inorganic",
    category: "equipment",
    name: "Dropper",
    symbol: "DRP",
    state: "device",
    accent: "#d24b2d",
    description: "For transfer of small amounts of liquids.",
  },
  {
    id: "forceps",
    module: "inorganic",
    category: "equipment",
    name: "Forceps",
    symbol: "FOR",
    state: "device",
    accent: "#cfd8e3",
    description: "Used to pick up small objects.",
  },
  {
    id: "clay-net",
    module: "inorganic",
    category: "equipment",
    name: "Clay Net",
    symbol: "NET",
    state: "device",
    accent: "#e8e6d9",
    description: "Ceramic wire net for supporting vessels while heating.",
  },
  {
    id: "retort-stand",
    module: "inorganic",
    category: "equipment",
    name: "Retort stand with clamp",
    symbol: "STD",
    state: "device",
    accent: "#cbd5e1",
    description: "Vertical support stand with clamp for holding glassware.",
  },
  {
    id: "cuo",
    module: "inorganic",
    category: "solids",
    name: "Copper (II) Oxide",
    symbol: "CuO",
    formula: "CuO",
    state: "solid",
    accent: "#111827",
    description: "Black oxide powder that glows when strongly heated.",
  },
  {
    id: "iron",
    module: "inorganic",
    category: "solids",
    name: "Iron Powder",
    symbol: "Fe",
    formula: "Fe",
    state: "solid",
    accent: "#94a3b8",
    description: "Fine grey iron powder for displacement reactions.",
  },
  {
    id: "sodium",
    module: "inorganic",
    category: "solids",
    name: "Sodium",
    symbol: "Na",
    formula: "Na",
    state: "solid",
    accent: "#f8fafc",
    description: "Highly reactive soft metal, simulated only.",
  },
  {
    id: "water",
    module: "inorganic",
    category: "liquids",
    name: "Distilled Water",
    symbol: "H2O",
    formula: "H2O",
    state: "liquid",
    accent: "#67e8f9",
    description: "Default solvent for dilution and washing.",
  },
  {
    id: "cuso4-solution",
    module: "inorganic",
    category: "liquids",
    name: "Copper Sulfate",
    symbol: "CuSO4",
    formula: "CuSO4(aq)",
    state: "liquid",
    accent: "#38bdf8",
    description: "Blue copper sulfate solution for displacement experiments.",
  },
  {
    id: "nacl-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium Chloride Solution",
    symbol: "NaCl",
    formula: "NaCl(aq)",
    state: "liquid",
    accent: "#e2e8f0",
    description: "Clear salt solution for conductivity and evaporation setup.",
  },
  {
    id: "co2",
    module: "inorganic",
    category: "gases",
    name: "Carbon Dioxide",
    symbol: "CO2",
    formula: "CO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Carbon dioxide gas for jar collection and extinguishing demos.",
  },
  {
    id: "match",
    module: "inorganic",
    category: "equipment",
    name: "Match",
    symbol: "MTH",
    state: "device",
    accent: "#f8eed3",
    description: "Single matchstick for ignition.",
    hidden: true, // Custom flag to hide from sidebar if we want
  },
];

export const ORGANIC_LIBRARY: OrganicLibraryItem[] = [
  {
    id: "atom-c",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "C",
    color: "#0f172a",
    description: "Carbon backbone atom.",
  },
  {
    id: "atom-h",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "H",
    color: "#e2e8f0",
    description: "Hydrogen atom.",
  },
  {
    id: "atom-o",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "O",
    color: "#ef4444",
    description: "Oxygen hetero atom.",
  },
  {
    id: "atom-n",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "N",
    color: "#3b82f6",
    description: "Nitrogen hetero atom.",
  },
  {
    id: "atom-cl",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Cl",
    color: "#22c55e",
    description: "Chloro substituent.",
  },
  {
    id: "atom-br",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Br",
    color: "#f97316",
    description: "Bromo substituent.",
  },
  {
    id: "ring-benzene",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Benzene",
    template: "benzene",
    color: "#ec4899",
    description: "Drop a six-member aromatic ring.",
  },
  {
    id: "ring-cyclohexane",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Cyclohexane",
    template: "cyclohexane",
    color: "#10b981",
    description: "Drop a six-member saturated ring.",
  },
  {
    id: "bond-single",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Single",
    order: 1,
    color: "#475569",
    description: "Create or update a single bond.",
  },
  {
    id: "bond-double",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Double",
    order: 2,
    color: "#475569",
    description: "Create or update a double bond.",
  },
  {
    id: "bond-triple",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Triple",
    order: 3,
    color: "#475569",
    description: "Create or update a triple bond.",
  },
  {
    id: "bond-aromatic",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Aromatic",
    order: "aromatic",
    color: "#8b5cf6",
    description: "Use for aromatic link styling.",
  },
  {
    id: "group-oh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "OH",
    color: "#ef4444",
    description: "Hydroxyl group fragment.",
  },
  {
    id: "group-cooh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "COOH",
    color: "#f97316",
    description: "Carboxylic acid fragment.",
  },
  {
    id: "group-nh2",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "NH2",
    color: "#3b82f6",
    description: "Primary amine fragment.",
  },
  {
    id: "group-ch3",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "CH3",
    color: "#0f172a",
    description: "Methyl fragment.",
  },
];

export function getCategoriesForModule(module: ChemistryModule): SidebarCategory[] {
  return module === "inorganic" ? INORGANIC_CATEGORIES : ORGANIC_CATEGORIES;
}

export function getLibraryForModule(module: ChemistryModule): ChemistryLibraryItem[] {
  return module === "inorganic" ? INORGANIC_LIBRARY : ORGANIC_LIBRARY;
}

export function getDefaultCategoryForModule(module: ChemistryModule): ChemistryCategory {
  return getCategoriesForModule(module)[0].id;
}
