import type {
  ChemistryCategory,
  ChemistryLibraryItem,
  ChemistryModule,
  InorganicLibraryItem,
  OrganicLibraryItem,
  SidebarCategory,
} from "./types";

export const INORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "glassware", name: "Reaction vessel", hint: "Flasks, tubes, funnels and reaction containers" },
  { id: "equipment", name: "Assistive devices", hint: "Heat, support, measuring and setup tools" },
  { id: "solids", name: "Solid chemical", hint: "Powders, salts and metal samples" },
  { id: "liquids", name: "Liquid reagents", hint: "Acids, solvents and solutions" },
  { id: "gases", name: "Gases", hint: "Common gaseous reactants and products" },
];

export const ORGANIC_CATEGORIES: SidebarCategory[] = [
  { id: "atoms", name: "Atoms", hint: "Place atoms and hetero atoms" },
  { id: "bonds", name: "Bonds", hint: "Create single, double and triple bonds" },
  { id: "rings", name: "Ring templates", hint: "Drop common cyclic scaffolds" },
  { id: "groups", name: "Groups", hint: "Quick functional-group fragments" },
];

export const INORGANIC_LIBRARY: InorganicLibraryItem[] = [
  {
    id: "beaker-100",
    module: "inorganic",
    category: "glassware",
    name: "Beaker (100 mL)",
    symbol: "BK100",
    state: "glassware",
    accent: "#cbd5e1",
    description: "The most basic glass laboratory container used for holding liquids, mixing substances, and preparing solutions.",
  },
  {
    id: "beaker-250",
    module: "inorganic",
    category: "glassware",
    name: "Beaker (250 mL)",
    symbol: "BK250",
    state: "glassware",
    accent: "#cbd5e1",
    description: "The most basic glass laboratory container used for holding liquids, mixing substances, and preparing solutions.",
  },
  {
    id: "beaker",
    module: "inorganic",
    category: "glassware",
    name: "Beaker (1000 mL)",
    symbol: "BK",
    state: "glassware",
    accent: "#cbd5e1",
    description: "The most basic glass laboratory container used for holding liquids, mixing substances, and preparing solutions.",
  },
  {
    id: "erlenmeyer-100",
    module: "inorganic",
    category: "glassware",
    name: "Erlenmeyer flask (100 mL)",
    symbol: "EF100",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Small conical flask for mixing and storing liquids.",
  },
  {
    id: "erlenmeyer-250",
    module: "inorganic",
    category: "glassware",
    name: "Erlenmeyer flask (250 mL)",
    symbol: "EF250",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Medium conical flask.",
  },
  {
    id: "three-neck-flask",
    module: "inorganic",
    category: "glassware",
    name: "Three-necked flask",
    symbol: "TNF",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Flask with three necks for complex setups.",
  },
  {
    id: "round-bottom-flask",
    module: "inorganic",
    category: "glassware",
    name: "Round Bottomed Flask",
    symbol: "RF",
    state: "glassware",
    accent: "#7f8ea3",
    description: "Heat-resistant glass vessel for boiling and reaction setup.",
  },
  {
    id: "separatory-funnel",
    module: "inorganic",
    category: "glassware",
    name: "Globe Shaped Separatory Funnel",
    symbol: "SF",
    state: "glassware",
    accent: "#d5dde7",
    description: "Round stopcock funnel for separating liquid layers.",
  },
  {
    id: "funnel",
    module: "inorganic",
    category: "glassware",
    name: "Funnel",
    symbol: "FNL",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Glass funnel for transferring liquids and filtration.",
  },
  {
    id: "funnel-100",
    module: "inorganic",
    category: "glassware",
    name: "Funnel (100 mL)",
    symbol: "FNL100",
    state: "glassware",
    accent: "#cbd5e1",
    description: "Small glass funnel for transferring liquids and filtration.",
  },
  {
    id: "gas-jar",
    module: "inorganic",
    category: "glassware",
    name: "Gas Jar",
    symbol: "GJ",
    state: "glassware",
    accent: "#d7dee8",
    description: "Wide cylindrical jar for collecting and observing gas.",
  },
  {
    id: "test-tube",
    module: "inorganic",
    category: "glassware",
    name: "Large Test Tube",
    symbol: "TT",
    state: "glassware",
    accent: "#14b8a6",
    description: "A cylindrical glass tube used for testing small quantities of solutions or for observing gas bubbles and reactions on a small scale.",
  },
  {
    id: "evaporation-chamber",
    module: "inorganic",
    category: "glassware",
    name: "Evaporation Chamber",
    symbol: "Chamber",
    formula: "Chamber",
    state: "glassware",
    accent: "#cbd5e1",
    description: "A specialized chamber designed for vaporization and containment of gaseous components.",
  },
  {
    id: "graduated-cylinder",
    module: "inorganic",
    category: "glassware",
    name: "Graduated Cylinder (100 mL)",
    symbol: "GC100",
    state: "glassware",
    accent: "#cbd5e1",
    description: "A tall, narrow glassware vessel used for measuring liquid volumes accurately.",
  },
  {
    id: "vacuum-chamber",
    module: "inorganic",
    category: "glassware",
    name: "Vacuum Chamber",
    symbol: "VAC",
    state: "glassware",
    accent: "#cbd5e1",
    description: "A thick-walled glass chamber designed for low-pressure reactions and gas adsorption.",
  },
  {
    id: "china-dish",
    module: "inorganic",
    category: "glassware",
    name: "Evaporating China Dish",
    symbol: "CD",
    state: "glassware",
    accent: "#cbd5e1",
    description: "A shallow porcelain dish with a spout used to evaporate liquids or mix amalgams.",
  },
  {
    id: "mortar-pestle",
    module: "inorganic",
    category: "glassware",
    name: "Mortar and Pestle",
    symbol: "MP",
    state: "glassware",
    accent: "#cbd5e1",
    description: "A grinding tool used to crush and mix solids and liquids (such as sodium and mercury) together to form a paste or amalgam.",
  },
  {
    id: "crucible",
    module: "inorganic",
    category: "glassware",
    name: "Clay Crucible",
    symbol: "CRU",
    state: "glassware",
    accent: "#78350f",
    description: "A small cup made of porcelain or ceramic that can withstand extremely high temperatures. It is used for melting metals and preparing solid–solid mixtures (alloys).",
  },
  {
    id: "glass-pipe",
    module: "inorganic",
    category: "equipment",
    name: "Glass Pipe (Bendable)",
    symbol: "PIPE",
    state: "device",
    accent: "#f8fafc",
    description: "A dynamic glass tube for connecting apparatus. Drag points to bend.",
  },
  {
    id: "burner",
    module: "inorganic",
    category: "equipment",
    name: "Alcohol Burner",
    symbol: "HT",
    state: "device",
    accent: "#fb7185",
    description: "Heat source for laboratory experiments.",
  },
  {
    id: "matchbox",
    module: "inorganic",
    category: "equipment",
    name: "Matchbox",
    symbol: "MBX",
    state: "device",
    accent: "#b44f50",
    description: "Matchbox with protruding matchstick for ignition demos.",
  },
  {
    id: "dropper",
    module: "inorganic",
    category: "equipment",
    name: "Dropper",
    symbol: "DRP",
    state: "device",
    accent: "#d24b2d",
    description: "For transfer of small amounts of liquids.",
  },
  {
    id: "forceps",
    module: "inorganic",
    category: "equipment",
    name: "Forceps",
    symbol: "FOR",
    state: "device",
    accent: "#cfd8e3",
    description: "Used to pick up small objects.",
  },
  {
    id: "clay-net",
    module: "inorganic",
    category: "equipment",
    name: "Clay Net",
    symbol: "NET",
    state: "device",
    accent: "#e8e6d9",
    description: "Ceramic wire net for supporting vessels while heating.",
  },
  {
    id: "retort-stand",
    module: "inorganic",
    category: "equipment",
    name: "Retort stand with clamp",
    symbol: "STD",
    state: "device",
    accent: "#cbd5e1",
    description: "Vertical support stand with clamp for holding glassware.",
  },
  {
    id: "gauze",
    module: "inorganic",
    category: "equipment",
    name: "Argil wire gauze",
    symbol: "GZ",
    state: "device",
    accent: "#cbd5e1",
    description: "Wire gauze with ceramic center for supporting and heating.",
  },
  {
    id: "ring-stand",
    module: "inorganic",
    category: "equipment",
    name: "Ring stand",
    symbol: "RSTD",
    state: "device",
    accent: "#cbd5e1",
    description: "Support stand with an iron ring.",
  },
  {
    id: "clamp",
    module: "inorganic",
    category: "equipment",
    name: "Clamp (side view)",
    symbol: "CLMP",
    state: "device",
    accent: "#cbd5e1",
    description: "Clamp for holding tubes or flasks securely.",
  },
  {
    id: "spatula",
    module: "inorganic",
    category: "equipment",
    name: "Spatula",
    symbol: "SPT",
    state: "device",
    accent: "#cbd5e1",
    description: "A small laboratory spoon used for safely handling, transferring, and removing chemical powders or solid substances.",
  },
  {
    id: "scissor",
    module: "inorganic",
    category: "equipment",
    name: "Scissors",
    symbol: "SCI",
    state: "device",
    accent: "#cbd5e1",
    description: "Used for cutting materials in the lab.",
  },
  {
    id: "thermometer",
    module: "inorganic",
    category: "equipment",
    name: "Thermometer",
    symbol: "THM",
    state: "device",
    accent: "#cbd5e1",
    description: "Used for measuring temperature.",
  },
  {
    id: "knife",
    module: "inorganic",
    category: "equipment",
    name: "Knife",
    symbol: "KNF",
    state: "device",
    accent: "#cbd5e1",
    description: "Used for cutting solids such as sodium or potassium.",
  },
  {
    id: "crucible-tongs",
    module: "inorganic",
    category: "equipment",
    name: "Crucible Tongs",
    symbol: "CTG",
    state: "device",
    accent: "#cbd5e1",
    description: "Used for handling hot crucibles and other apparatus.",
  },
  {
    id: "glass-conduit",
    module: "inorganic",
    category: "equipment",
    name: "90-degree glass conduit",
    symbol: "COND",
    state: "device",
    accent: "#cbd5e1",
    description: "A 90-degree glass tube for connecting apparatus and directing gas.",
  },
  {
    id: "glass-stopper",
    module: "inorganic",
    category: "equipment",
    name: "Glass Stopper",
    symbol: "Stopper",
    state: "device",
    accent: "#cbd5e1",
    description: "A glass stopper for chemical bottles.",
    hidden: true,
  },
  {
    id: "cork-stopper",
    module: "inorganic",
    category: "equipment",
    name: "Cork Stopper",
    symbol: "Cork",
    state: "device",
    accent: "#d97706",
    description: "A cork stopper for chemical bottles.",
    hidden: true,
  },
  {
    id: "burner-cap",
    module: "inorganic",
    category: "equipment",
    name: "Burner Cap",
    symbol: "Cap",
    state: "device",
    accent: "#dbe4ef",
    description: "A snuffer cap for the alcohol burner.",
    hidden: true,
  },
  {
    id: "glass-plate",
    module: "inorganic",
    category: "equipment",
    name: "Glass Plate",
    symbol: "Plate",
    state: "device",
    accent: "#cbd5e1",
    description: "A glass cover plate for gas jars.",
    hidden: true,
  },
  {
    id: "heating-mantle",
    module: "inorganic",
    category: "equipment",
    name: "Heating Mantle",
    symbol: "Mantle",
    state: "device",
    accent: "#cbd5e1",
    description: "An electrical heating device designed to fit and heat round-bottom flasks.",
  },
  {
    id: "stirring-rod",
    module: "inorganic",
    category: "equipment",
    name: "Glass Stirring Rod",
    symbol: "ROD",
    state: "device",
    accent: "#f8fafc",
    description: "Used for quickly and safely stirring or mixing solids (such as glucose) into liquids.",
  },
  {
    id: "gas-inlet-valve",
    module: "inorganic",
    category: "equipment",
    name: "Gas Inlet Valve",
    symbol: "VALVE",
    state: "device",
    accent: "#d97706",
    description: "A rotary control valve for regulating gas flow into the vacuum chamber.",
  },
  {
    id: "safety-gloves",
    module: "inorganic",
    category: "equipment",
    name: "Safety Gloves",
    symbol: "GLOVES",
    state: "device",
    accent: "#38bdf8",
    description: "Safety Note: When working in a laboratory with chemicals such as chloroform, ethanol, mercury (Hg), or sodium metal, always wear appropriate safety equipment, including: Safety Goggles, Protective Gloves, Lab Coat. When handling volatile or toxic substances, especially mercury, ensure proper ventilation and preferably work inside a Fume Hood. Always follow laboratory safety protocols and guidelines.",
  },
  {
    id: "furnace",
    module: "inorganic",
    category: "equipment",
    name: "High-Temp Furnace",
    symbol: "FURNACE",
    state: "device",
    accent: "#374151",
    description: "An electric furnace capable of reaching temperatures over 1000°C for melting metals.",
  },
  {
    id: "tongs",
    module: "inorganic",
    category: "equipment",
    name: "Crucible Tongs",
    symbol: "TONGS",
    state: "device",
    accent: "#64748b",
    description: "Scissor-like metal tongs used to safely handle hot crucibles.",
  },

  {
    id: "palladium-plate",
    module: "inorganic",
    category: "solids",
    name: "Palladium Plate",
    symbol: "Pd",
    formula: "Pd",
    state: "solid",
    accent: "#cbd5e1",
    description: "A clean silver-grey palladium metal plate.",
  },
  {
    id: "palladium-adsorbed",
    module: "inorganic",
    category: "solids",
    name: "Adsorbed Palladium Plate",
    symbol: "Pd-H",
    formula: "Pd(H2)x",
    state: "solid",
    accent: "#93c5fd",
    description: "A palladium metal plate containing adsorbed hydrogen gas molecules.",
  },
  {
    id: "sodium-amalgam",
    module: "inorganic",
    category: "solids",
    name: "Sodium Amalgam",
    symbol: "Na-Hg",
    formula: "Na(Hg)x",
    state: "solid",
    accent: "#cbd5e1",
    description: "A semi-solid silvery-grey amalgam paste of sodium and mercury.",
  },
  {
    id: "gold-powder",
    module: "inorganic",
    category: "solids",
    name: "Gold powder",
    symbol: "Au",
    formula: "Au",
    state: "solid",
    accent: "#f59e0b",
    description: "Pure gold metallic powder, shiny yellow color.",
  },
  {
    id: "gold-copper-alloy",
    module: "inorganic",
    category: "solids",
    name: "Gold-Copper Alloy",
    symbol: "Au-Cu",
    formula: "Au-Cu",
    state: "solid",
    accent: "#ea580c",
    description: "A solid metallic alloy of gold and copper, reddish-gold color.",
  },
  {
    id: "cuo",
    module: "inorganic",
    category: "solids",
    name: "Copper (II) Oxide",
    symbol: "CuO",
    formula: "CuO",
    state: "solid",
    accent: "#111827",
    description: "Black oxide powder that glows when strongly heated.",
  },
  {
    id: "iron",
    module: "inorganic",
    category: "solids",
    name: "Iron Powder",
    symbol: "Fe",
    formula: "Fe",
    state: "solid",
    accent: "#94a3b8",
    description: "Fine grey iron powder for displacement reactions.",
  },
  {
    id: "sodium",
    module: "inorganic",
    category: "solids",
    name: "Sodium",
    symbol: "Na",
    formula: "Na",
    state: "solid",
    accent: "#f8fafc",
    description: "Highly reactive soft metal, simulated only.",
  },
  {
    id: "kclo3",
    module: "inorganic",
    category: "solids",
    name: "Potassium chlorate",
    symbol: "KClO3",
    formula: "KClO3",
    state: "solid",
    accent: "#e2e8f0",
    description: "White crystalline solid used in chemical reactions.",
  },
  {
    id: "kmno4",
    module: "inorganic",
    category: "solids",
    name: "Potassium permanganate",
    symbol: "KMnO4",
    formula: "KMnO4",
    state: "solid",
    accent: "#2e0854",
    description: "Dark purple crystalline compound, a strong oxidizing agent.",
  },
  {
    id: "mno2",
    module: "inorganic",
    category: "solids",
    name: "Manganese dioxide",
    symbol: "MnO2",
    formula: "MnO2",
    state: "solid",
    accent: "#1e293b",
    description: "Black inorganic compound used as a catalyst.",
  },
  {
    id: "sodium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Sodium carbonate",
    symbol: "Na2CO3",
    formula: "Na2CO3",
    state: "solid",
    accent: "#e2e8f0",
    description: "White odorless powder, used in glass and soap production.",
  },
  {
    id: "sodium-peroxide",
    module: "inorganic",
    category: "solids",
    name: "Sodium peroxide",
    symbol: "Na2O2",
    formula: "Na2O2",
    state: "solid",
    accent: "#fef08a",
    description: "Yellowish solid compound, a strong oxidizer.",
  },
  {
    id: "sucrose",
    module: "inorganic",
    category: "solids",
    name: "Sucrose",
    symbol: "C12H22O11",
    formula: "C12H22O11",
    state: "solid",
    accent: "#f8fafc",
    description: "Common sugar, white crystalline carbohydrate.",
  },
  {
    id: "iron-nail",
    module: "inorganic",
    category: "solids",
    name: "Iron nail",
    symbol: "Fe",
    formula: "Fe",
    state: "solid",
    accent: "#94a3b8",
    description: "A small metal nail composed primarily of iron.",
  },
  {
    id: "thermite",
    module: "inorganic",
    category: "solids",
    name: "Thermite",
    symbol: "Al/Fe2O3",
    formula: "Al/Fe2O3",
    state: "solid",
    accent: "#7c2d12",
    description: "A mixture of metal powder and metal oxide that undergoes a highly exothermic reaction.",
  },
  {
    id: "sand",
    module: "inorganic",
    category: "solids",
    name: "Sand",
    symbol: "SiO2",
    formula: "SiO2",
    state: "solid",
    accent: "#b45309",
    description: "Granular material composed of finely divided rock and mineral particles.",
  },
  {
    id: "silver",
    module: "inorganic",
    category: "solids",
    name: "Silver",
    symbol: "Ag",
    formula: "Ag",
    state: "solid",
    accent: "#cbd5e1",
    description: "Shiny metallic silver element in powder form.",
  },
  {
    id: "silver-sulfide",
    module: "inorganic",
    category: "solids",
    name: "Silver sulfide",
    symbol: "Ag2S",
    formula: "Ag2S",
    state: "solid",
    accent: "#1e293b",
    description: "Dark grey/black inorganic compound, insoluble in water.",
  },
  {
    id: "silver-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Silver sulfate",
    symbol: "Ag2SO4",
    formula: "Ag2SO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "White/grey ionic compound of silver used in chemical testing.",
  },
  {
    id: "silver-chloride",
    module: "inorganic",
    category: "solids",
    name: "Silver chloride",
    symbol: "AgCl",
    formula: "AgCl",
    state: "solid",
    accent: "#e2e8f0",
    description: "White crystalline chemical compound, well known for its low solubility in water.",
  },
  {
    id: "silver-iodide",
    module: "inorganic",
    category: "solids",
    name: "Silver iodide",
    symbol: "AgI",
    formula: "AgI",
    state: "solid",
    accent: "#eab308",
    description: "Highly photosensitive bright yellow solid compound.",
  },
  {
    id: "silver-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Silver nitrate",
    symbol: "AgNO3",
    formula: "AgNO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, extremely versatile precursor to many other silver compounds.",
  },
  {
    id: "aluminum-powder",
    module: "inorganic",
    category: "solids",
    name: "Aluminum powder",
    symbol: "Al",
    formula: "Al",
    state: "solid",
    accent: "#94a3b8",
    description: "Finely divided aluminum metal powder.",
  },
  {
    id: "alumina",
    module: "inorganic",
    category: "solids",
    name: "Alumina",
    symbol: "Al2O3",
    formula: "Al2O3",
    state: "solid",
    accent: "#f8fafc",
    description: "Chemical compound of aluminum and oxygen, commonly called aluminum oxide.",
  },
  {
    id: "aluminum-sulfide",
    module: "inorganic",
    category: "solids",
    name: "Aluminum sulfide",
    symbol: "Al2S3",
    formula: "Al2S3",
    state: "solid",
    accent: "#334155",
    description: "Greyish-black chemical compound prepared by heating aluminum and sulfur.",
  },
  {
    id: "aluminum-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Aluminum sulfate",
    symbol: "Al2(SO4)3",
    formula: "Al2(SO4)3",
    state: "solid",
    accent: "#f1f5f9",
    description: "White crystalline compound, soluble in water.",
  },
  {
    id: "aluminum-bromide",
    module: "inorganic",
    category: "solids",
    name: "Aluminum bromide",
    symbol: "AlBr3",
    formula: "AlBr3",
    state: "solid",
    accent: "#cbd5e1",
    description: "Pale yellow or white crystalline solid, highly reactive with water.",
  },
  {
    id: "aluminum-chloride",
    module: "inorganic",
    category: "solids",
    name: "Aluminum chloride",
    symbol: "AlCl3",
    formula: "AlCl3",
    state: "solid",
    accent: "#f8fafc",
    description: "Main compound of aluminum and chlorine, white to yellow solid.",
  },
  {
    id: "aluminum-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Aluminum nitrate",
    symbol: "Al(NO3)3",
    formula: "Al(NO3)3",
    state: "solid",
    accent: "#f8fafc",
    description: "White, water-soluble salt of aluminum and nitric acid.",
  },
  {
    id: "aluminum-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Aluminum hydroxide",
    symbol: "Al(OH)3",
    formula: "Al(OH)3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound found in nature as the mineral gibbsite.",
  },
  {
    id: "barium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Barium chloride",
    symbol: "BaCl2",
    formula: "BaCl2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic salt, one of the most common water-soluble salts of barium.",
  },
  {
    id: "barium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Barium carbonate",
    symbol: "BaCO3",
    formula: "BaCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "White insoluble powder widely used in the ceramics industry.",
  },
  {
    id: "barium-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Barium nitrate",
    symbol: "Ba(NO3)2",
    formula: "Ba(NO3)2",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline solid compound of barium and nitrate.",
  },
  {
    id: "barium-oxide",
    module: "inorganic",
    category: "solids",
    name: "Barium oxide",
    symbol: "BaO",
    formula: "BaO",
    state: "solid",
    accent: "#f1f5f9",
    description: "White hygroscopic compound formed by heating barium carbonate.",
  },
  {
    id: "barium-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Barium hydroxide",
    symbol: "Ba(OH)2",
    formula: "Ba(OH)2",
    state: "solid",
    accent: "#f8fafc",
    description: "White granular solid compound, chemical precursor of other barium compounds.",
  },
  {
    id: "barium-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Barium sulfate",
    symbol: "BaSO4",
    formula: "BaSO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "White crystalline solid, odorless and insoluble in water.",
  },
  {
    id: "charcoal",
    module: "inorganic",
    category: "solids",
    name: "Charcoal",
    symbol: "C",
    formula: "C",
    state: "solid",
    accent: "#1e293b",
    description: "Lightweight black carbon residue produced by strongly heating wood.",
  },
  {
    id: "calcium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Calcium chloride",
    symbol: "CaCl2",
    formula: "CaCl2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic salt, highly soluble in water, white crystalline solid.",
  },
  {
    id: "calcium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Calcium carbonate",
    symbol: "CaCO3",
    formula: "CaCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Common substance found in rocks, main component of pearls and shells.",
  },
  {
    id: "calcium-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Calcium nitrate",
    symbol: "Ca(NO3)2",
    formula: "Ca(NO3)2",
    state: "solid",
    accent: "#f8fafc",
    description: "Colorless salt that absorbs moisture from the air, mainly used in fertilizers.",
  },
  {
    id: "calcium-oxide",
    module: "inorganic",
    category: "solids",
    name: "Calcium oxide",
    symbol: "CaO",
    formula: "CaO",
    state: "solid",
    accent: "#f1f5f9",
    description: "Widely used chemical compound, commonly known as quicklime.",
  },
  {
    id: "calcium-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Calcium hydroxide",
    symbol: "Ca(OH)2",
    formula: "Ca(OH)2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, white powder obtained when quicklime is slaked with water.",
  },
  {
    id: "calcium-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Calcium sulfate",
    symbol: "CaSO4",
    formula: "CaSO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "Inorganic compound, common hydrate forms are plaster of Paris and gypsum.",
  },
  {
    id: "copper-powder",
    module: "inorganic",
    category: "solids",
    name: "Copper powder",
    symbol: "Cu",
    formula: "Cu",
    state: "solid",
    accent: "#ea580c",
    description: "Pure metallic copper in fine powder form, reddish-brown color.",
  },
  {
    id: "cuprous-sulfide",
    module: "inorganic",
    category: "solids",
    name: "Cuprous sulfide",
    symbol: "Cu2S",
    formula: "Cu2S",
    state: "solid",
    accent: "#0f172a",
    description: "Copper(I) sulfide, a black solid compound found in nature as chalcocite.",
  },
  {
    id: "copper-chloride",
    module: "inorganic",
    category: "solids",
    name: "Copper chloride",
    symbol: "CuCl2",
    formula: "CuCl2",
    state: "solid",
    accent: "#ca8a04",
    description: "Light brown anhydrous copper(II) chloride compound.",
  },
  {
    id: "copper-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Copper nitrate",
    symbol: "Cu(NO3)2",
    formula: "Cu(NO3)2",
    state: "solid",
    accent: "#2563eb",
    description: "Deep blue crystalline inorganic copper compound.",
  },
  {
    id: "copper-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Copper hydroxide",
    symbol: "Cu(OH)2",
    formula: "Cu(OH)2",
    state: "solid",
    accent: "#0284c7",
    description: "Pale blue solid compound of copper and hydroxide.",
  },
  {
    id: "copper-sulfate-pentahydrate",
    module: "inorganic",
    category: "solids",
    name: "Copper sulfate pentahydrate",
    symbol: "CuSO4·5H2O",
    formula: "CuSO4·5H2O",
    state: "solid",
    accent: "#3b82f6",
    description: "Bright blue crystalline hydrate of copper sulfate.",
  },
  {
    id: "copper-sulfate-anhydrous",
    module: "inorganic",
    category: "solids",
    name: "Copper sulfate",
    symbol: "CuSO4",
    formula: "CuSO4",
    state: "solid",
    accent: "#cbd5e1",
    description: "White/grey anhydrous copper sulfate powder.",
  },
  {
    id: "iron-oxide-red",
    module: "inorganic",
    category: "solids",
    name: "Iron oxide",
    symbol: "Fe2O3",
    formula: "Fe2O3",
    state: "solid",
    accent: "#9a3412",
    description: "Reddish-brown inorganic compound, iron(III) oxide.",
  },
  {
    id: "ferric-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Ferric sulfate",
    symbol: "Fe2(SO4)3",
    formula: "Fe2(SO4)3",
    state: "solid",
    accent: "#eab308",
    description: "Yellowish crystalline salt of iron(III) and sulfate.",
  },
  {
    id: "ferric-oxide-black",
    module: "inorganic",
    category: "solids",
    name: "Ferric oxide",
    symbol: "Fe3O4",
    formula: "Fe3O4",
    state: "solid",
    accent: "#111827",
    description: "Black iron oxide mineral compound, iron(II,III) oxide.",
  },
  {
    id: "ferrous-chloride",
    module: "inorganic",
    category: "solids",
    name: "Ferrous chloride",
    symbol: "FeCl2",
    formula: "FeCl2",
    state: "solid",
    accent: "#16a34a",
    description: "Greenish-white dihydrate compound of iron(II) and chloride.",
  },
  {
    id: "ferric-chloride",
    module: "inorganic",
    category: "solids",
    name: "Ferric chloride",
    symbol: "FeCl3",
    formula: "FeCl3",
    state: "solid",
    accent: "#854d0e",
    description: "Orange-brown crystalline compound of iron(III) and chloride.",
  },
  {
    id: "ferrous-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Ferrous nitrate",
    symbol: "Fe(NO3)2",
    formula: "Fe(NO3)2",
    state: "solid",
    accent: "#10b981",
    description: "Light green crystalline iron(II) nitrate compound.",
  },
  {
    id: "ferric-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Ferric nitrate",
    symbol: "Fe(NO3)3",
    formula: "Fe(NO3)3",
    state: "solid",
    accent: "#c084fc",
    description: "Pale violet crystalline compound of iron(III) nitrate.",
  },
  {
    id: "ferrous-oxide",
    module: "inorganic",
    category: "solids",
    name: "Ferrous oxide",
    symbol: "FeO",
    formula: "FeO",
    state: "solid",
    accent: "#0f172a",
    description: "Black powder, iron(II) oxide.",
  },
  {
    id: "ferrous-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Ferrous hydroxide",
    symbol: "Fe(OH)2",
    formula: "Fe(OH)2",
    state: "solid",
    accent: "#e2e8f0",
    description: "White-greenish compound formed when iron(II) salts react with hydroxide ions.",
  },
  {
    id: "ferric-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Ferric hydroxide",
    symbol: "Fe(OH)3",
    formula: "Fe(OH)3",
    state: "solid",
    accent: "#7c2d12",
    description: "Reddish-brown compound of iron(III) and hydroxide.",
  },
  {
    id: "ferrous-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Ferrous sulfate",
    symbol: "FeSO4",
    formula: "FeSO4",
    state: "solid",
    accent: "#4ade80",
    description: "Light green iron(II) sulfate compound, copperas.",
  },
  {
    id: "mercuric-oxide",
    module: "inorganic",
    category: "solids",
    name: "Mercuric oxide",
    symbol: "HgO",
    formula: "HgO",
    state: "solid",
    accent: "#dc2626",
    description: "Red or orange solid compound of mercury and oxygen.",
  },
  {
    id: "iodine",
    module: "inorganic",
    category: "solids",
    name: "Iodine",
    symbol: "I2",
    formula: "I2",
    state: "solid",
    accent: "#1e1b4b",
    description: "Dark purple-black crystalline halogen element.",
  },
  {
    id: "potassium-manganate",
    module: "inorganic",
    category: "solids",
    name: "Potassium manganate",
    symbol: "K2MnO4",
    formula: "K2MnO4",
    state: "solid",
    accent: "#064e3b",
    description: "Dark green crystalline compound, intermediate in the synthesis of potassium permanganate.",
  },
  {
    id: "potassium-oxide",
    module: "inorganic",
    category: "solids",
    name: "Potassium oxide",
    symbol: "K2O",
    formula: "K2O",
    state: "solid",
    accent: "#f8fafc",
    description: "An inorganic compound of potassium and oxygen, highly reactive with water.",
  },
  {
    id: "potassium-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Potassium sulfate",
    symbol: "K2SO4",
    formula: "K2SO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "White crystalline inorganic salt compound.",
  },
  {
    id: "potassium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Potassium chloride",
    symbol: "KCl",
    formula: "KCl",
    state: "solid",
    accent: "#f8fafc",
    description: "Metal halide salt composed of potassium and chlorine.",
  },
  {
    id: "potassium-iodide",
    module: "inorganic",
    category: "solids",
    name: "Potassium iodide",
    symbol: "KI",
    formula: "KI",
    state: "solid",
    accent: "#f8fafc",
    description: "Chemical compound, medication, and dietary supplement.",
  },
  {
    id: "potassium-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Potassium nitrate",
    symbol: "KNO3",
    formula: "KNO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic salt, commonly called saltpeter.",
  },
  {
    id: "potassium-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Potassium hydroxide",
    symbol: "KOH",
    formula: "KOH",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, commonly called caustic potash.",
  },
  {
    id: "potassium-ferrocyanide",
    module: "inorganic",
    category: "solids",
    name: "Potassium ferrocyanide",
    symbol: "K4[Fe(CN)6]",
    formula: "K4[Fe(CN)6]",
    state: "solid",
    accent: "#f59e0b",
    description: "Yellow/orange coordination complex salt compound.",
  },
  {
    id: "magnesium-powder",
    module: "inorganic",
    category: "solids",
    name: "Magnesium powder",
    symbol: "Mg",
    formula: "Mg",
    state: "solid",
    accent: "#d1d5db",
    description: "Finely divided magnesium metal powder, highly flammable.",
  },
  {
    id: "magnesium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Magnesium chloride",
    symbol: "MgCl2",
    formula: "MgCl2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic chemical compound consisting of magnesium and chlorine.",
  },
  {
    id: "magnesium-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Magnesium nitrate",
    symbol: "Mg(NO3)2",
    formula: "Mg(NO3)2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, a highly hygroscopic salt.",
  },
  {
    id: "magnesium-oxide",
    module: "inorganic",
    category: "solids",
    name: "Magnesium oxide",
    symbol: "MgO",
    formula: "MgO",
    state: "solid",
    accent: "#f1f5f9",
    description: "White hygroscopic solid mineral compound, magnesia.",
  },
  {
    id: "magnesium-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Magnesium hydroxide",
    symbol: "Mg(OH)2",
    formula: "Mg(OH)2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, occurs in nature as the mineral brucite.",
  },
  {
    id: "magnesium-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Magnesium sulfate",
    symbol: "MgSO4",
    formula: "MgSO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "Inorganic chemical salt, Epsom salt.",
  },
  {
    id: "manganese-chloride",
    module: "inorganic",
    category: "solids",
    name: "Manganese chloride",
    symbol: "MnCl2",
    formula: "MnCl2",
    state: "solid",
    accent: "#f472b6",
    description: "Pinkish manganese(II) chloride salt compound.",
  },
  {
    id: "magnesium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Magnesium carbonate",
    symbol: "MgCO3",
    formula: "MgCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic salt, white insoluble solid.",
  },
  {
    id: "sodium-oxide-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium oxide",
    symbol: "Na2O",
    formula: "Na2O",
    state: "solid",
    accent: "#f1f5f9",
    description: "Alkali metal oxide compound of sodium and oxygen.",
  },
  {
    id: "sodium-sulfite",
    module: "inorganic",
    category: "solids",
    name: "Sodium sulfite",
    symbol: "Na2SO3",
    formula: "Na2SO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Soluble sodium salt of sulfurous acid.",
  },
  {
    id: "sodium-sulfate-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium sulfate",
    symbol: "Na2SO4",
    formula: "Na2SO4",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic sodium salt of sulfuric acid.",
  },
  {
    id: "sodium-chloride-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium chloride",
    symbol: "NaCl",
    formula: "NaCl",
    state: "solid",
    accent: "#f8fafc",
    description: "Common table salt, an ionic compound.",
  },
  {
    id: "sodium-bicarbonate",
    module: "inorganic",
    category: "solids",
    name: "Sodium bicarbonate",
    symbol: "NaHCO3",
    formula: "NaHCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Commonly known as baking soda, white crystalline solid.",
  },
  {
    id: "sodium-bisulfate",
    module: "inorganic",
    category: "solids",
    name: "Sodium bisulfate",
    symbol: "NaHSO4",
    formula: "NaHSO4",
    state: "solid",
    accent: "#f8fafc",
    description: "Sodium acid sulfate compound, dry acid.",
  },
  {
    id: "sodium-nitrate-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium nitrate",
    symbol: "NaNO3",
    formula: "NaNO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Alkali metal nitrate salt, Chile saltpeter.",
  },
  {
    id: "sodium-hydroxide-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium hydroxide",
    symbol: "NaOH",
    formula: "NaOH",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, commonly known as caustic soda or lye.",
  },
  {
    id: "ammonium-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Ammonium sulfate",
    symbol: "(NH4)2SO4",
    formula: "(NH4)2SO4",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic sulfate salt, widely used as a soil fertilizer.",
  },
  {
    id: "ammonium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Ammonium chloride",
    symbol: "NH4Cl",
    formula: "NH4Cl",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, highly soluble white crystalline salt.",
  },
  {
    id: "ammonium-nitrate",
    module: "inorganic",
    category: "solids",
    name: "Ammonium nitrate",
    symbol: "NH4NO3",
    formula: "NH4NO3",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline chemical compound consisting of ammonium and nitrate.",
  },
  {
    id: "red-phosphorus",
    module: "inorganic",
    category: "solids",
    name: "Red phosphorus",
    symbol: "P",
    formula: "P",
    state: "solid",
    accent: "#b91c1c",
    description: "Allotrope of phosphorus, dark red amorphous powder.",
  },
  {
    id: "white-phosphorus",
    module: "inorganic",
    category: "solids",
    name: "White phosphorus",
    symbol: "P",
    formula: "P",
    state: "solid",
    accent: "#e2e8f0",
    description: "Waxy white/greyish solid allotrope of phosphorus, stored under water.",
  },
  {
    id: "phosphorus-pentoxide",
    module: "inorganic",
    category: "solids",
    name: "Phosphorus pentoxide",
    symbol: "P2O5",
    formula: "P2O5",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic oxide compound, powerful dehydrating agent.",
  },
  {
    id: "lead-metal",
    module: "inorganic",
    category: "solids",
    name: "Lead",
    symbol: "Pb",
    formula: "Pb",
    state: "solid",
    accent: "#94a3b8",
    description: "Heavy post-transition metal element, bluish-grey color.",
  },
  {
    id: "lead-chloride",
    module: "inorganic",
    category: "solids",
    name: "Lead chloride",
    symbol: "PbCl2",
    formula: "PbCl2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, lead(II) chloride.",
  },
  {
    id: "lead-dioxide",
    module: "inorganic",
    category: "solids",
    name: "Lead dioxide",
    symbol: "PbO2",
    formula: "PbO2",
    state: "solid",
    accent: "#1e293b",
    description: "Inorganic compound, lead(IV) oxide.",
  },
  {
    id: "platinum-powder",
    module: "inorganic",
    category: "solids",
    name: "Platinum powder",
    symbol: "Pt",
    formula: "Pt",
    state: "solid",
    accent: "#94a3b8",
    description: "Noble transition metal powder, highly unreactive.",
  },
  {
    id: "sulfur-powder",
    module: "inorganic",
    category: "solids",
    name: "Sulfur powder",
    symbol: "S",
    formula: "S",
    state: "solid",
    accent: "#eab308",
    description: "Bright yellow crystalline nonmetal powder element.",
  },
  {
    id: "silicon",
    module: "inorganic",
    category: "solids",
    name: "Silicon",
    symbol: "Si",
    formula: "Si",
    state: "solid",
    accent: "#334155",
    description: "Hard, brittle crystalline solid with a blue-grey metallic luster.",
  },
  {
    id: "zinc-powder",
    module: "inorganic",
    category: "solids",
    name: "Zinc powder",
    symbol: "Zn",
    formula: "Zn",
    state: "solid",
    accent: "#94a3b8",
    description: "Finely divided zinc metal powder, bluish-grey color.",
  },
  {
    id: "zinc-chloride",
    module: "inorganic",
    category: "solids",
    name: "Zinc chloride",
    symbol: "ZnCl2",
    formula: "ZnCl2",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline ionic salt compound, highly deliquescent.",
  },
  {
    id: "zinc-sulfate",
    module: "inorganic",
    category: "solids",
    name: "Zinc sulfate",
    symbol: "ZnSO4",
    formula: "ZnSO4",
    state: "solid",
    accent: "#f1f5f9",
    description: "Inorganic compound, historically known as white vitriol.",
  },
  {
    id: "marble-rocks",
    module: "inorganic",
    category: "solids",
    name: "Marble rocks",
    symbol: "CaCO3",
    formula: "CaCO3",
    state: "solid",
    accent: "#cbd5e1",
    description: "Metamorphic rock composed of recrystallized carbonate minerals.",
  },
  {
    id: "silica",
    module: "inorganic",
    category: "solids",
    name: "Silica",
    symbol: "SiO2",
    formula: "SiO2",
    state: "solid",
    accent: "#f8fafc",
    description: "Oxide of silicon, most commonly found in nature as quartz.",
  },
  {
    id: "basic-copper-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Basic copper carbonate",
    symbol: "Cu2(OH)2CO3",
    formula: "Cu2(OH)2CO3",
    state: "solid",
    accent: "#10b981",
    description: "Green chemical compound, main component of the patina that forms on copper.",
  },
  {
    id: "activated-carbon",
    module: "inorganic",
    category: "solids",
    name: "Activated carbon",
    symbol: "C",
    formula: "C",
    state: "solid",
    accent: "#111827",
    description: "Form of carbon processed to have small, low-volume pores that increase surface area.",
  },
  {
    id: "sodium-acetate-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium acetate",
    symbol: "CH3COONa",
    formula: "CH3COONa",
    state: "solid",
    accent: "#f8fafc",
    description: "Sodium salt of acetic acid, white crystalline solid.",
  },
  {
    id: "sodium-sulfide-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium sulfide",
    symbol: "Na2S",
    formula: "Na2S",
    state: "solid",
    accent: "#f1f5f9",
    description: "Chemical compound of sodium and sulfur, water-soluble salt.",
  },
  {
    id: "sodium-hydrosulfide",
    module: "inorganic",
    category: "solids",
    name: "Sodium hydrosulfide",
    symbol: "NaHS",
    formula: "NaHS",
    state: "solid",
    accent: "#1e293b",
    description: "Chemical compound, useful reagent for synthesis of organic and inorganic sulfur compounds.",
  },
  {
    id: "silver-hydroxide",
    module: "inorganic",
    category: "solids",
    name: "Silver hydroxide",
    symbol: "AgOH",
    formula: "AgOH",
    state: "solid",
    accent: "#cbd5e1",
    description: "Inorganic compound, unstable compound that readily converts to silver oxide.",
  },
  {
    id: "ammonium-bicarbonate",
    module: "inorganic",
    category: "solids",
    name: "Ammonium bicarbonate",
    symbol: "NH4HCO3",
    formula: "NH4HCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, decomposes to ammonia, carbon dioxide and water.",
  },
  {
    id: "ammonium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Ammonium carbonate",
    symbol: "(NH4)2CO3",
    formula: "(NH4)2CO3",
    state: "solid",
    accent: "#f1f5f9",
    description: "Salt chemical compound, main component of smelling salts.",
  },
  {
    id: "crude-salt",
    module: "inorganic",
    category: "solids",
    name: "Crude salt",
    symbol: "NaCl/KCl/...",
    formula: "NaCl/KCl/...",
    state: "solid",
    accent: "#e2e8f0",
    description: "Unrefined mineral salt containing various trace elements.",
  },
  {
    id: "sodium-thiosulfate-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium thiosulfate",
    symbol: "Na2S2O3",
    formula: "Na2S2O3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, typical hydrate is pentahydrate salt.",
  },
  {
    id: "manganese-sulfate-solid",
    module: "inorganic",
    category: "solids",
    name: "Manganese sulfate",
    symbol: "MnSO4",
    formula: "MnSO4",
    state: "solid",
    accent: "#fce7f3",
    description: "Inorganic compound of manganese and sulfate, pale pink salt.",
  },
  {
    id: "potassium-dichromate",
    module: "inorganic",
    category: "solids",
    name: "Potassium dichromate",
    symbol: "K2Cr2O7",
    formula: "K2Cr2O7",
    state: "solid",
    accent: "#f97316",
    description: "Bright orange inorganic chemical reagent compound.",
  },
  {
    id: "potassium-thiocyanate",
    module: "inorganic",
    category: "solids",
    name: "Potassium thiocyanate",
    symbol: "KSCN",
    formula: "KSCN",
    state: "solid",
    accent: "#f8fafc",
    description: "Chemical compound, potassium salt of thiocyanic acid.",
  },
  {
    id: "seaweed-ash",
    module: "inorganic",
    category: "solids",
    name: "Seaweed ash",
    symbol: "K2CO3/NaCl...",
    formula: "K2CO3/NaCl...",
    state: "solid",
    accent: "#475569",
    description: "Ash obtained by burning seaweed, rich in potassium carbonate and mineral salts.",
  },
  {
    id: "barium-hydroxide-octahydrate",
    module: "inorganic",
    category: "solids",
    name: "Barium hydroxide octahydrate",
    symbol: "Ba(OH)2·8H2O",
    formula: "Ba(OH)2·8H2O",
    state: "solid",
    accent: "#f8fafc",
    description: "Highly stable octahydrate crystal form of barium hydroxide.",
  },
  {
    id: "boric-acid-solid",
    module: "inorganic",
    category: "solids",
    name: "Boric acid",
    symbol: "H3BO3",
    formula: "H3BO3",
    state: "solid",
    accent: "#f1f5f9",
    description: "Weak, monobasic Lewis acid of boron, white powder.",
  },
  {
    id: "sodium-iodide-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium iodide",
    symbol: "NaI",
    formula: "NaI",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline ionic salt compound of sodium and iodine.",
  },
  {
    id: "sodium-bromide-solid",
    module: "inorganic",
    category: "solids",
    name: "Sodium bromide",
    symbol: "NaBr",
    formula: "NaBr",
    state: "solid",
    accent: "#f1f5f9",
    description: "White crystalline inorganic salt, widely used source of bromide ion.",
  },
  {
    id: "zeolite",
    module: "inorganic",
    category: "solids",
    name: "Zeolite",
    symbol: "AlxSiyOz",
    formula: "AlxSiyOz",
    state: "solid",
    accent: "#e2e8f0",
    description: "Microporous, aluminosilicate mineral compound.",
  },
  {
    id: "blue-copperas",
    module: "inorganic",
    category: "solids",
    name: "Blue copperas",
    symbol: "CuSO4·5H2O",
    formula: "CuSO4·5H2O",
    state: "solid",
    accent: "#2563eb",
    description: "Deep blue copper sulfate pentahydrate crystalline compound.",
  },
  {
    id: "silver-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Silver carbonate",
    symbol: "Ag2CO3",
    formula: "Ag2CO3",
    state: "solid",
    accent: "#fef08a",
    description: "Yellowish chemical compound of silver and carbonate.",
  },
  {
    id: "charcoal-powder",
    module: "inorganic",
    category: "solids",
    name: "Charcoal powder",
    symbol: "C",
    formula: "C",
    state: "solid",
    accent: "#1e293b",
    description: "Finely ground charcoal carbon powder.",
  },
  {
    id: "glucose",
    module: "inorganic",
    category: "solids",
    name: "Glucose",
    symbol: "C6H12O6",
    formula: "C6H12O6",
    state: "solid",
    accent: "#f8fafc",
    description: "Simple sugar/monosaccharide, white crystalline solid.",
  },
  {
    id: "cuprous-oxide",
    module: "inorganic",
    category: "solids",
    name: "Cuprous oxide",
    symbol: "Cu2O",
    formula: "Cu2O",
    state: "solid",
    accent: "#b91c1c",
    description: "Inorganic compound, copper(I) oxide, red powder solid.",
  },
  {
    id: "polyethylene",
    module: "inorganic",
    category: "solids",
    name: "Polyethylene",
    symbol: "PE",
    formula: "PE",
    state: "solid",
    accent: "#f8fafc",
    description: "Common thermoplastic polymer solid compound.",
  },
  {
    id: "manganese-metal",
    module: "inorganic",
    category: "solids",
    name: "Manganese",
    symbol: "Mn",
    formula: "Mn",
    state: "solid",
    accent: "#94a3b8",
    description: "Transition metal element, silvery-grey color.",
  },
  {
    id: "calcium-hypochlorite",
    module: "inorganic",
    category: "solids",
    name: "Calcium hypochlorite",
    symbol: "Ca(ClO)2",
    formula: "Ca(ClO)2",
    state: "solid",
    accent: "#f1f5f9",
    description: "Inorganic compound, active ingredient of bleaching powder.",
  },
  {
    id: "copper-sulfide-solid",
    module: "inorganic",
    category: "solids",
    name: "Copper sulfide",
    symbol: "CuS",
    formula: "CuS",
    state: "solid",
    accent: "#0f172a",
    description: "Copper(II) sulfide, black chemical compound.",
  },
  {
    id: "potassium-bicarbonate",
    module: "inorganic",
    category: "solids",
    name: "Potassium bicarbonate",
    symbol: "KHCO3",
    formula: "KHCO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Colorless, odorless, salty basic compound salt.",
  },
  {
    id: "potassium-carbonate",
    module: "inorganic",
    category: "solids",
    name: "Potassium carbonate",
    symbol: "K2CO3",
    formula: "K2CO3",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, white salt soluble in water, pearl ash.",
  },
  {
    id: "potassium-metal",
    module: "inorganic",
    category: "solids",
    name: "Potassium",
    symbol: "K",
    formula: "K",
    state: "solid",
    accent: "#cbd5e1",
    description: "Soft alkali metal, highly reactive, stored under mineral oil.",
  },
  {
    id: "calcium-metal",
    module: "inorganic",
    category: "solids",
    name: "Calcium",
    symbol: "Ca",
    formula: "Ca",
    state: "solid",
    accent: "#94a3b8",
    description: "Alkaline earth metal, reactive element, grey solid.",
  },
  {
    id: "copper-wire-segment",
    module: "inorganic",
    category: "solids",
    name: "Copper wire segment",
    symbol: "Cu",
    formula: "Cu",
    state: "solid",
    accent: "#b45309",
    description: "Ductile copper metal wire segment segments.",
  },
  {
    id: "lead-nitrate-solid",
    module: "inorganic",
    category: "solids",
    name: "Lead nitrate",
    symbol: "Pb(NO3)2",
    formula: "Pb(NO3)2",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic compound, lead(II) nitrate salt.",
  },
  {
    id: "magnesium-ribbon",
    module: "inorganic",
    category: "solids",
    name: "Short magnesium ribbon",
    symbol: "Mg",
    formula: "Mg",
    state: "solid",
    accent: "#cbd5e1",
    description: "Thin ribbons of magnesium metal, highly reactive.",
  },
  {
    id: "aluminum-sheet",
    module: "inorganic",
    category: "solids",
    name: "Aluminum sheet",
    symbol: "Al",
    formula: "Al",
    state: "solid",
    accent: "#cbd5e1",
    description: "Thin metal sheets of aluminum.",
  },
  {
    id: "lead-acetate",
    module: "inorganic",
    category: "solids",
    name: "Lead acetate",
    symbol: "Pb(CH3COO)2",
    formula: "Pb(CH3COO)2",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline chemical compound, sugar of lead.",
  },
  {
    id: "copper-sheet",
    module: "inorganic",
    category: "solids",
    name: "Small copper sheet",
    symbol: "Cu",
    formula: "Cu",
    state: "solid",
    accent: "#ea580c",
    description: "Thin metallic copper sheet.",
  },
  {
    id: "silver-acetylide",
    module: "inorganic",
    category: "solids",
    name: "Silver acetylide",
    symbol: "Ag2C2",
    formula: "Ag2C2",
    state: "solid",
    accent: "#e2e8f0",
    description: "Organometallic chemical compound, highly explosive solid.",
  },
  {
    id: "sodium-percarbonate",
    module: "inorganic",
    category: "solids",
    name: "Sodium percarbonate",
    symbol: "Na2C2O6",
    formula: "Na2C2O6",
    state: "solid",
    accent: "#f8fafc",
    description: "Inorganic chemical adduct of sodium carbonate and hydrogen peroxide.",
  },
  {
    id: "zinc-granule",
    module: "inorganic",
    category: "solids",
    name: "Zinc granule",
    symbol: "Zn",
    formula: "Zn",
    state: "solid",
    accent: "#94a3b8",
    description: "Bluish-grey metallic zinc granules.",
  },
  {
    id: "paraffin-wax",
    module: "inorganic",
    category: "solids",
    name: "Paraffin",
    symbol: "Paraffin",
    formula: "Paraffin",
    state: "solid",
    accent: "#f1f5f9",
    description: "Waxy white solid hydrocarbon mixture.",
  },
  {
    id: "lithium-chloride-solid",
    module: "inorganic",
    category: "solids",
    name: "Lithium chloride",
    symbol: "LiCl",
    formula: "LiCl",
    state: "solid",
    accent: "#f8fafc",
    description: "Alkali metal halide ionic salt compound.",
  },
  {
    id: "caesium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Caesium chloride",
    symbol: "CsCl",
    formula: "CsCl",
    state: "solid",
    accent: "#f1f5f9",
    description: "Inorganic chloride salt compound of caesium.",
  },
  {
    id: "strontium-chloride",
    module: "inorganic",
    category: "solids",
    name: "Strontium chloride",
    symbol: "SrCl2",
    formula: "SrCl2",
    state: "solid",
    accent: "#cbd5e1",
    description: "Inorganic salt of strontium and chloride, white crystalline powder.",
  },
  {
    id: "camphor",
    module: "inorganic",
    category: "solids",
    name: "Camphor",
    symbol: "C10H16O",
    formula: "C10H16O",
    state: "solid",
    accent: "#f8fafc",
    description: "White crystalline substance with a strong aromatic odor, undergoes sublimation when heated.",
  },
  {
    id: "water",
    module: "inorganic",
    category: "liquids",
    name: "Distilled water",
    symbol: "H2O",
    formula: "H2O",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Default solvent for dilution and washing.",
  },
  {
    id: "cuso4-solution",
    module: "inorganic",
    category: "liquids",
    name: "Copper sulfate solution",
    symbol: "CuSO4",
    formula: "CuSO4",
    state: "liquid",
    accent: "#3b82f6",
    description: "Blue copper sulfate solution.",
  },
  {
    id: "nacl-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium chloride solution",
    symbol: "NaCl",
    formula: "NaCl",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium chloride salt solution.",
  },
  {
    id: "sodium-hydroxide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium hydroxide solution",
    symbol: "NaOH",
    formula: "NaOH",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear basic sodium hydroxide solution.",
  },
  {
    id: "concentrated-sulfuric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Concentrated sulfuric acid",
    symbol: "H2SO4",
    formula: "H2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Strong concentrated mineral acid sulfuric acid.",
  },
  {
    id: "dilute-sulfuric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Dilute sulfuric acid",
    symbol: "H2SO4",
    formula: "H2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Diluted sulfuric acid solution.",
  },
  {
    id: "dilute-hydrochloric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Dilute hydrochloric acid",
    symbol: "HCl",
    formula: "HCl",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Diluted hydrochloric acid solution.",
  },
  {
    id: "phenolphthalein",
    module: "inorganic",
    category: "liquids",
    name: "Phenolphthalein",
    symbol: "Phenolphthalein",
    formula: "Phenolphthalein",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Acid-base indicator, colorless in acid and pink in base.",
  },
  {
    id: "clear-lime-water",
    module: "inorganic",
    category: "liquids",
    name: "Clear lime water",
    symbol: "Ca(OH)2",
    formula: "Ca(OH)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear calcium hydroxide solution, turns milky in presence of carbon dioxide.",
  },
  {
    id: "soapy-water",
    module: "inorganic",
    category: "liquids",
    name: "Soapy water",
    symbol: "C17H35COONa",
    formula: "C17H35COONa",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Solution of soap in water, used for bubble tests.",
  },
  {
    id: "litmus",
    module: "inorganic",
    category: "liquids",
    name: "Litmus",
    symbol: "Litmus",
    formula: "Litmus",
    state: "liquid",
    accent: "#6366f1",
    description: "Water-soluble mixture of different dyes, pH indicator.",
  },
  {
    id: "silver-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Silver nitrate solution",
    symbol: "AgNO3",
    formula: "AgNO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear silver nitrate solution, stored in amber bottle.",
  },
  {
    id: "aluminum-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Aluminum sulfate solution",
    symbol: "Al2(SO4)3",
    formula: "Al2(SO4)3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear aluminum sulfate solution.",
  },
  {
    id: "aluminum-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Aluminum chloride solution",
    symbol: "AlCl3",
    formula: "AlCl3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear aluminum chloride solution.",
  },
  {
    id: "aluminum-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Aluminum nitrate solution",
    symbol: "Al(NO3)3",
    formula: "Al(NO3)3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear aluminum nitrate solution.",
  },
  {
    id: "barium-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Barium chloride solution",
    symbol: "BaCl2",
    formula: "BaCl2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear barium chloride solution.",
  },
  {
    id: "barium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Barium nitrate solution",
    symbol: "Ba(NO3)2",
    formula: "Ba(NO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear barium nitrate solution.",
  },
  {
    id: "barium-hydroxide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Barium hydroxide solution",
    symbol: "Ba(OH)2",
    formula: "Ba(OH)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear barium hydroxide solution.",
  },
  {
    id: "bromine",
    module: "inorganic",
    category: "liquids",
    name: "Bromine",
    symbol: "Br2",
    formula: "Br2",
    state: "liquid",
    accent: "#991b1b",
    description: "Reddish-brown halogen liquid element.",
  },
  {
    id: "calcium-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Calcium chloride solution",
    symbol: "CaCl2",
    formula: "CaCl2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear calcium chloride solution.",
  },
  {
    id: "calcium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Calcium nitrate solution",
    symbol: "Ca(NO3)2",
    formula: "Ca(NO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear calcium nitrate solution.",
  },
  {
    id: "carbon-tetrachloride",
    module: "inorganic",
    category: "liquids",
    name: "Carbon tetrachloride",
    symbol: "CCl4",
    formula: "CCl4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear, heavy carbon tetrachloride organic solvent liquid.",
  },
  {
    id: "copper-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Copper chloride solution",
    symbol: "CuCl2",
    formula: "CuCl2",
    state: "liquid",
    accent: "#0d9488",
    description: "Blue-green copper(II) chloride solution.",
  },
  {
    id: "copper-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Copper nitrate solution",
    symbol: "Cu(NO3)2",
    formula: "Cu(NO3)2",
    state: "liquid",
    accent: "#2563eb",
    description: "Blue copper(II) nitrate solution.",
  },
  {
    id: "ferrous-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferrous sulfate solution",
    symbol: "FeSO4",
    formula: "FeSO4",
    state: "liquid",
    accent: "#65a30d",
    description: "Pale green ferrous sulfate solution.",
  },
  {
    id: "ferrous-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferrous chloride solution",
    symbol: "FeCl2",
    formula: "FeCl2",
    state: "liquid",
    accent: "#4d7c0f",
    description: "Pale green ferrous chloride solution.",
  },
  {
    id: "ferric-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferric chloride solution",
    symbol: "FeCl3",
    formula: "FeCl3",
    state: "liquid",
    accent: "#d97706",
    description: "Yellow-brown ferric chloride solution.",
  },
  {
    id: "ferrous-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferrous nitrate solution",
    symbol: "Fe(NO3)2",
    formula: "Fe(NO3)2",
    state: "liquid",
    accent: "#4d7c0f",
    description: "Pale green ferrous nitrate solution.",
  },
  {
    id: "ferric-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferric nitrate solution",
    symbol: "Fe(NO3)3",
    formula: "Fe(NO3)3",
    state: "liquid",
    accent: "#d97706",
    description: "Pale yellow/amber ferric nitrate solution.",
  },
  {
    id: "ferric-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ferric sulfate solution",
    symbol: "Fe2(SO4)3",
    formula: "Fe2(SO4)3",
    state: "liquid",
    accent: "#d97706",
    description: "Pale yellow/amber ferric sulfate solution.",
  },
  {
    id: "sulfur-trioxide",
    module: "inorganic",
    category: "liquids",
    name: "Sulfur trioxide",
    symbol: "SO3",
    formula: "SO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sulfur trioxide liquid compound.",
  },
  {
    id: "sulfite-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sulfite",
    symbol: "H2SO3",
    formula: "H2SO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sulfurous acid / sulfite solution.",
  },
  {
    id: "sulfuric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Sulfuric acid",
    symbol: "H2SO4",
    formula: "H2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sulfuric acid solution.",
  },
  {
    id: "potassium-manganate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium manganate solution",
    symbol: "K2MnO4",
    formula: "K2MnO4",
    state: "liquid",
    accent: "#047857",
    description: "Dark green potassium manganate solution.",
  },
  {
    id: "potassium-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium sulfate solution",
    symbol: "K2SO4",
    formula: "K2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium sulfate solution.",
  },
  {
    id: "potassium-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium chloride solution",
    symbol: "KCl",
    formula: "KCl",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium chloride solution.",
  },
  {
    id: "potassium-chlorate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium chlorate solution",
    symbol: "KClO3",
    formula: "KClO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium chlorate solution.",
  },
  {
    id: "potassium-iodide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium iodide solution",
    symbol: "KI",
    formula: "KI",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium iodide solution.",
  },
  {
    id: "potassium-permanganate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium permanganate solution",
    symbol: "KMnO4",
    formula: "KMnO4",
    state: "liquid",
    accent: "#701a75",
    description: "Deep purple potassium permanganate solution, stored in amber bottle.",
  },
  {
    id: "potassium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium nitrate solution",
    symbol: "KNO3",
    formula: "KNO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium nitrate solution.",
  },
  {
    id: "potassium-hydroxide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium hydroxide solution",
    symbol: "KOH",
    formula: "KOH",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium hydroxide basic solution.",
  },
  {
    id: "potassium-ferrocyanide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium ferrocyanide solution",
    symbol: "K4[Fe(CN)6]",
    formula: "K4[Fe(CN)6]",
    state: "liquid",
    accent: "#eab308",
    description: "Yellow potassium ferrocyanide solution.",
  },
  {
    id: "magnesium-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Magnesium chloride solution",
    symbol: "MgCl2",
    formula: "MgCl2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear magnesium chloride solution.",
  },
  {
    id: "magnesium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Magnesium nitrate solution",
    symbol: "Mg(NO3)2",
    formula: "Mg(NO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear magnesium nitrate solution.",
  },
  {
    id: "magnesium-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Magnesium sulfate solution",
    symbol: "MgSO4",
    formula: "MgSO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear magnesium sulfate solution.",
  },
  {
    id: "manganese-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Manganese chloride solution",
    symbol: "MnCl2",
    formula: "MnCl2",
    state: "liquid",
    accent: "#f472b6",
    description: "Pale pink manganese chloride solution.",
  },
  {
    id: "sodium-carbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium carbonate solution",
    symbol: "Na2CO3",
    formula: "Na2CO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium carbonate basic solution.",
  },
  {
    id: "sodium-sulfite-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium sulfite solution",
    symbol: "Na2SO3",
    formula: "Na2SO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium sulfite solution.",
  },
  {
    id: "sodium-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium sulfate solution",
    symbol: "Na2SO4",
    formula: "Na2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium sulfate solution.",
  },
  {
    id: "sodium-bicarbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium bicarbonate solution",
    symbol: "NaHCO3",
    formula: "NaHCO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium bicarbonate basic solution.",
  },
  {
    id: "sodium-bisulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium bisulfate solution",
    symbol: "NaHSO4",
    formula: "NaHSO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium bisulfate acidic solution.",
  },
  {
    id: "sodium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium nitrate solution",
    symbol: "NaNO3",
    formula: "NaNO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium nitrate solution.",
  },
  {
    id: "ammonium-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ammonium sulfate solution",
    symbol: "(NH4)2SO4",
    formula: "(NH4)2SO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear ammonium sulfate solution.",
  },
  {
    id: "ammonium-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ammonium chloride solution",
    symbol: "NH4Cl",
    formula: "NH4Cl",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear ammonium chloride solution.",
  },
  {
    id: "ammonium-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ammonium nitrate solution",
    symbol: "NH4NO3",
    formula: "NH4NO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear ammonium nitrate solution.",
  },
  {
    id: "zinc-chloride-solution",
    module: "inorganic",
    category: "liquids",
    name: "Zinc chloride solution",
    symbol: "ZnCl2",
    formula: "ZnCl2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear zinc chloride solution.",
  },
  {
    id: "zinc-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Zinc sulfate solution",
    symbol: "ZnSO4",
    formula: "ZnSO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear zinc sulfate solution.",
  },
  {
    id: "sucrose-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sucrose solution",
    symbol: "C12H22O11",
    formula: "C12H22O11",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sugar sucrose solution.",
  },
  {
    id: "concentrated-hydrochloric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Concentrated hydrochloric acid",
    symbol: "HCl",
    formula: "HCl",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Strong concentrated mineral hydrochloric acid.",
  },
  {
    id: "concentrated-nitric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Concentrated nitric acid",
    symbol: "HNO3",
    formula: "HNO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Strong concentrated nitric acid.",
  },
  {
    id: "dilute-nitric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Dilute nitric acid",
    symbol: "HNO3",
    formula: "HNO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Diluted nitric acid solution.",
  },
  {
    id: "dilute-acetic-acid",
    module: "inorganic",
    category: "liquids",
    name: "Dilute acetic acid",
    symbol: "CH3COOH",
    formula: "CH3COOH",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Diluted acetic acid solution.",
  },
  {
    id: "sodium-silicate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium silicate solution",
    symbol: "Na2SiO3",
    formula: "Na2SiO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium silicate solution.",
  },
  {
    id: "ammonia-water",
    module: "inorganic",
    category: "liquids",
    name: "Ammonia water",
    symbol: "NH3·H2O",
    formula: "NH3·H2O",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Aqueous ammonium hydroxide basic solution.",
  },
  {
    id: "calcium-bicarbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Calcium bicarbonate solution",
    symbol: "Ca(HCO3)2",
    formula: "Ca(HCO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear calcium bicarbonate solution.",
  },
  {
    id: "sodium-acetate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium acetate solution",
    symbol: "CH3COONa",
    formula: "CH3COONa",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium acetate solution.",
  },
  {
    id: "sodium-sulfide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium sulfide solution",
    symbol: "Na2S",
    formula: "Na2S",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium sulfide solution.",
  },
  {
    id: "sodium-hydrosulfide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium hydrosulfide solution",
    symbol: "NaHS",
    formula: "NaHS",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium hydrosulfide solution.",
  },
  {
    id: "ammonium-bicarbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ammonium bicarbonate solution",
    symbol: "NH4HCO3",
    formula: "NH4HCO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear ammonium bicarbonate solution.",
  },
  {
    id: "ammonium-carbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ammonium carbonate solution",
    symbol: "(NH4)2CO3",
    formula: "(NH4)2CO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear ammonium carbonate solution.",
  },
  {
    id: "iodine-water",
    module: "inorganic",
    category: "liquids",
    name: "Iodine water",
    symbol: "I2",
    formula: "I2",
    state: "liquid",
    accent: "#b45309",
    description: "Yellow-brown aqueous iodine solution.",
  },
  {
    id: "sodium-thiosulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium thiosulfate solution",
    symbol: "Na2S2O3",
    formula: "Na2S2O3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium thiosulfate solution.",
  },
  {
    id: "hydrogen-peroxide",
    module: "inorganic",
    category: "liquids",
    name: "Hydrogen peroxide",
    symbol: "H2O2",
    formula: "H2O2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear hydrogen peroxide solution.",
  },
  {
    id: "manganese-sulfate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Manganese sulfate solution",
    symbol: "MnSO4",
    formula: "MnSO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear manganese sulfate solution.",
  },
  {
    id: "potassium-dichromate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium bichromate solution",
    symbol: "K2Cr2O7",
    formula: "K2Cr2O7",
    state: "liquid",
    accent: "#f97316",
    description: "Bright orange potassium dichromate solution.",
  },
  {
    id: "potassium-thiocyanate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium thiocyanate solution",
    symbol: "KSCN",
    formula: "KSCN",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium thiocyanate solution.",
  },
  {
    id: "ethanol",
    module: "inorganic",
    category: "liquids",
    name: "Ethanol",
    symbol: "C2H5OH",
    formula: "C2H5OH",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear organic alcohol liquid.",
  },
  {
    id: "ethanol-solution",
    module: "inorganic",
    category: "liquids",
    name: "Ethanol and Water Solution",
    symbol: "C2H5OH + H2O",
    formula: "C2H5OH + H2O",
    state: "liquid",
    accent: "#cbd5e1",
    description: "A uniform homogeneous single-phase solution of ethanol and water.",
  },
  {
    id: "mercury",
    module: "inorganic",
    category: "liquids",
    name: "Mercury",
    symbol: "Hg",
    formula: "Hg",
    state: "liquid",
    accent: "#94a3b8",
    description: "Dense, silvery liquid metal (toxic). Handle with care.",
  },
  {
    id: "sodium-hypochlorite",
    module: "inorganic",
    category: "liquids",
    name: "Sodium hypochlorite",
    symbol: "NaClO",
    formula: "NaClO",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium hypochlorite bleaching solution.",
  },
  {
    id: "starch-solution",
    module: "inorganic",
    category: "liquids",
    name: "Starch solution",
    symbol: "(C6H10O5)n",
    formula: "(C6H10O5)n",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Cloudy white starch indicator solution.",
  },
  {
    id: "boric-acid-solution",
    module: "inorganic",
    category: "liquids",
    name: "Boric acid solution",
    symbol: "H3BO3",
    formula: "H3BO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear boric acid solution.",
  },
  {
    id: "sodium-iodide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium iodide solution",
    symbol: "NaI",
    formula: "NaI",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium iodide solution.",
  },
  {
    id: "sodium-bromide-solution",
    module: "inorganic",
    category: "liquids",
    name: "Sodium bromide solution",
    symbol: "NaBr",
    formula: "NaBr",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear sodium bromide solution.",
  },
  {
    id: "chlorine-water",
    module: "inorganic",
    category: "liquids",
    name: "Chlorine water",
    symbol: "Cl2",
    formula: "Cl2",
    state: "liquid",
    accent: "#fef08a",
    description: "Pale yellow chlorine water solution.",
  },
  {
    id: "bromine-water",
    module: "inorganic",
    category: "liquids",
    name: "Bromine water",
    symbol: "Br2",
    formula: "Br2",
    state: "liquid",
    accent: "#ea580c",
    description: "Orange-brown bromine water solution.",
  },
  {
    id: "fuchsin-solution",
    module: "inorganic",
    category: "liquids",
    name: "Fuchsin solution",
    symbol: "Fuchsin",
    formula: "Fuchsin",
    state: "liquid",
    accent: "#db2777",
    description: "Deep magenta fuchsin dye solution.",
  },
  {
    id: "hard-water",
    module: "inorganic",
    category: "liquids",
    name: "Hard water",
    symbol: "Hard water",
    formula: "Hard water",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Water containing high mineral content.",
  },
  {
    id: "tap-water",
    module: "inorganic",
    category: "liquids",
    name: "Tap water",
    symbol: "Tap water",
    formula: "Tap water",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Untreated drinking tap water.",
  },
  {
    id: "glucose-solution",
    module: "inorganic",
    category: "liquids",
    name: "Glucose solution",
    symbol: "C6H12O6",
    formula: "C6H12O6",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear glucose sugar solution.",
  },
  {
    id: "acetic-acid",
    module: "inorganic",
    category: "liquids",
    name: "Acetic acid",
    symbol: "CH3COOH",
    formula: "CH3COOH",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear concentrated acetic acid liquid.",
  },
  {
    id: "barium-bicarbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Barium bicarbonate solution",
    symbol: "Ba(HCO3)2",
    formula: "Ba(HCO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear barium bicarbonate solution.",
  },
  {
    id: "calcium-hypochlorite-solution",
    module: "inorganic",
    category: "liquids",
    name: "Calcium hypochlorite solution",
    symbol: "Ca(ClO)2",
    formula: "Ca(ClO)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear calcium hypochlorite bleaching solution.",
  },
  {
    id: "potassium-bicarbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium bicarbonate solution",
    symbol: "KHCO3",
    formula: "KHCO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium bicarbonate solution.",
  },
  {
    id: "potassium-carbonate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Potassium carbonate solution",
    symbol: "K2CO3",
    formula: "K2CO3",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear potassium carbonate solution.",
  },
  {
    id: "phosphoric-acid",
    module: "inorganic",
    category: "liquids",
    name: "Phosphoric acid",
    symbol: "H3PO4",
    formula: "H3PO4",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear mineral phosphoric acid liquid.",
  },
  {
    id: "lead-nitrate-solution",
    module: "inorganic",
    category: "liquids",
    name: "Lead nitrate solution",
    symbol: "Pb(NO3)2",
    formula: "Pb(NO3)2",
    state: "liquid",
    accent: "#cbd5e1",
    description: "Clear lead nitrate solution.",
  },
  {
    id: "methyl-orange",
    module: "inorganic",
    category: "liquids",
    name: "Methyl orange",
    symbol: "Methyl orange",
    formula: "Methyl orange",
    state: "liquid",
    accent: "#ea580c",
    description: "Orange-red methyl orange pH indicator solution.",
  },
  {
    id: "chloroform",
    module: "inorganic",
    category: "liquids",
    name: "Chloroform",
    symbol: "CHCl3",
    formula: "CHCl3",
    state: "liquid",
    accent: "#f1f5f9",
    description: "Clear, colorless organic chloroform solvent liquid.",
  },
  {
    id: "co2",
    module: "inorganic",
    category: "gases",
    name: "Carbon dioxide",
    symbol: "CO2",
    formula: "CO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Carbon dioxide gas in a gas jar.",
  },
  {
    id: "chloroform-vapor",
    module: "inorganic",
    category: "gases",
    name: "Chloroform Vapor",
    symbol: "CHCl3 (g)",
    formula: "CHCl3",
    state: "gas",
    accent: "#cbd5e1",
    description: "Colorless vaporous chloroform gas.",
  },
  {
    id: "mist",
    module: "inorganic",
    category: "gases",
    name: "Mist",
    symbol: "Mist",
    formula: "Mist",
    state: "gas",
    accent: "#f1f5f9",
    description: "Condensation droplets in gas (fog/mist).",
  },
  {
    id: "camphor-vapor",
    module: "inorganic",
    category: "gases",
    name: "Camphor Vapor",
    symbol: "C10H16O (g)",
    formula: "C10H16O",
    state: "gas",
    accent: "#cbd5e1",
    description: "Colorless aromatic sublimated camphor vapor.",
  },
  {
    id: "carbon-monoxide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Carbon monoxide gasbag",
    symbol: "CO",
    formula: "CO",
    state: "gas",
    accent: "#cbd5e1",
    description: "Carbon monoxide gas stored in a gasbag.",
  },
  {
    id: "hydrogen-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen gasbag",
    symbol: "H2",
    formula: "H2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen gas stored in a gasbag.",
  },
  {
    id: "ammonia-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Ammonia gasbag",
    symbol: "NH3",
    formula: "NH3",
    state: "gas",
    accent: "#cbd5e1",
    description: "Ammonia gas stored in a gasbag.",
  },
  {
    id: "oxygen",
    module: "inorganic",
    category: "gases",
    name: "Oxygen",
    symbol: "O2",
    formula: "O2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Oxygen gas in a gas jar.",
  },
  {
    id: "oxygen-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Oxygen gasbag",
    symbol: "O2",
    formula: "O2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Oxygen gas stored in a gasbag.",
  },
  {
    id: "acetylene-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Acetylene gasbag",
    symbol: "C2H2",
    formula: "C2H2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Acetylene gas stored in a gasbag.",
  },
  {
    id: "argon",
    module: "inorganic",
    category: "gases",
    name: "Argon",
    symbol: "Ar",
    formula: "Ar",
    state: "gas",
    accent: "#cbd5e1",
    description: "Argon gas in a gas jar.",
  },
  {
    id: "argon-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Argon gasbag",
    symbol: "Ar",
    formula: "Ar",
    state: "gas",
    accent: "#cbd5e1",
    description: "Argon gas stored in a gasbag.",
  },
  {
    id: "chlorine",
    module: "inorganic",
    category: "gases",
    name: "Chlorine",
    symbol: "Cl2",
    formula: "Cl2",
    state: "gas",
    accent: "#a3e635",
    description: "Chlorine gas in a gas jar.",
  },
  {
    id: "chlorine-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Chlorine gasbag",
    symbol: "Cl2",
    formula: "Cl2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Chlorine gas stored in a gasbag.",
  },
  {
    id: "carbon-monoxide",
    module: "inorganic",
    category: "gases",
    name: "Carbon monoxide",
    symbol: "CO",
    formula: "CO",
    state: "gas",
    accent: "#cbd5e1",
    description: "Carbon monoxide gas in a gas jar.",
  },
  {
    id: "carbon-dioxide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Carbon dioxide gasbag",
    symbol: "CO2",
    formula: "CO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Carbon dioxide gas stored in a gasbag.",
  },
  {
    id: "fluorine",
    module: "inorganic",
    category: "gases",
    name: "Fluorine",
    symbol: "F2",
    formula: "F2",
    state: "gas",
    accent: "#86efac",
    description: "Fluorine gas in a gas jar.",
  },
  {
    id: "fluorine-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Fluorine gasbag",
    symbol: "F2",
    formula: "F2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Fluorine gas stored in a gasbag.",
  },
  {
    id: "hydrogen",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen",
    symbol: "H2",
    formula: "H2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen gas in a gas jar.",
  },
  {
    id: "hydrogen-sulfide",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen sulfide",
    symbol: "H2S",
    formula: "H2S",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen sulfide gas in a gas jar.",
  },
  {
    id: "hydrogen-sulfide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen sulfide gasbag",
    symbol: "H2S",
    formula: "H2S",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen sulfide gas stored in a gasbag.",
  },
  {
    id: "hydrogen-chloride",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen chloride",
    symbol: "HCl",
    formula: "HCl",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen chloride gas in a gas jar.",
  },
  {
    id: "hydrogen-chloride-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen chloride gasbag",
    symbol: "HCl",
    formula: "HCl",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen chloride gas stored in a gasbag.",
  },
  {
    id: "helium",
    module: "inorganic",
    category: "gases",
    name: "Helium",
    symbol: "He",
    formula: "He",
    state: "gas",
    accent: "#cbd5e1",
    description: "Helium gas in a gas jar.",
  },
  {
    id: "helium-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Helium gasbag",
    symbol: "He",
    formula: "He",
    state: "gas",
    accent: "#cbd5e1",
    description: "Helium gas stored in a gasbag.",
  },
  {
    id: "nitrogen",
    module: "inorganic",
    category: "gases",
    name: "Nitrogen",
    symbol: "N2",
    formula: "N2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Nitrogen gas in a gas jar.",
  },
  {
    id: "nitrogen-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Nitrogen gasbag",
    symbol: "N2",
    formula: "N2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Nitrogen gas stored in a gasbag.",
  },
  {
    id: "neon",
    module: "inorganic",
    category: "gases",
    name: "Neon",
    symbol: "Ne",
    formula: "Ne",
    state: "gas",
    accent: "#cbd5e1",
    description: "Neon gas in a gas jar.",
  },
  {
    id: "neon-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Neon gasbag",
    symbol: "Ne",
    formula: "Ne",
    state: "gas",
    accent: "#cbd5e1",
    description: "Neon gas stored in a gasbag.",
  },
  {
    id: "ammonia",
    module: "inorganic",
    category: "gases",
    name: "Ammonia",
    symbol: "NH3",
    formula: "NH3",
    state: "gas",
    accent: "#cbd5e1",
    description: "Ammonia gas in a gas jar.",
  },
  {
    id: "nitric-oxide",
    module: "inorganic",
    category: "gases",
    name: "Nitric oxide",
    symbol: "NO",
    formula: "NO",
    state: "gas",
    accent: "#cbd5e1",
    description: "Nitric oxide gas in a gas jar.",
  },
  {
    id: "nitric-oxide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Nitric oxide gasbag",
    symbol: "NO",
    formula: "NO",
    state: "gas",
    accent: "#cbd5e1",
    description: "Nitric oxide gas stored in a gasbag.",
  },
  {
    id: "nitrogen-dioxide",
    module: "inorganic",
    category: "gases",
    name: "Nitrogen dioxide",
    symbol: "NO2",
    formula: "NO2",
    state: "gas",
    accent: "#ea580c",
    description: "Nitrogen dioxide gas in a gas jar.",
  },
  {
    id: "nitric-dioxide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Nitric dioxide gasbag",
    symbol: "NO2",
    formula: "NO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Nitrogen dioxide gas stored in a gasbag.",
  },
  {
    id: "sulfur-dioxide",
    module: "inorganic",
    category: "gases",
    name: "Sulfur dioxide",
    symbol: "SO2",
    formula: "SO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Sulfur dioxide gas in a gas jar.",
  },
  {
    id: "sulfur-dioxide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Sulfur dioxide gasbag",
    symbol: "SO2",
    formula: "SO2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Sulfur dioxide gas stored in a gasbag.",
  },
  {
    id: "air",
    module: "inorganic",
    category: "gases",
    name: "Air",
    symbol: "Air",
    formula: "Air",
    state: "gas",
    accent: "#cbd5e1",
    description: "Atmospheric air in a gas jar.",
  },
  {
    id: "air-filled-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Air filled gasbag",
    symbol: "Air",
    formula: "Air",
    state: "gas",
    accent: "#cbd5e1",
    description: "Atmospheric air stored in a gasbag.",
  },
  {
    id: "methane",
    module: "inorganic",
    category: "gases",
    name: "Methane",
    symbol: "CH4",
    formula: "CH4",
    state: "gas",
    accent: "#cbd5e1",
    description: "Methane gas in a gas jar.",
  },
  {
    id: "methane-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Methane gasbag",
    symbol: "CH4",
    formula: "CH4",
    state: "gas",
    accent: "#cbd5e1",
    description: "Methane gas stored in a gasbag.",
  },
  {
    id: "acetylene",
    module: "inorganic",
    category: "gases",
    name: "Acetylene",
    symbol: "C2H2",
    formula: "C2H2",
    state: "gas",
    accent: "#cbd5e1",
    description: "Acetylene gas in a gas jar.",
  },
  {
    id: "ethylene",
    module: "inorganic",
    category: "gases",
    name: "Ethylene",
    symbol: "C2H4",
    formula: "C2H4",
    state: "gas",
    accent: "#cbd5e1",
    description: "Ethylene gas in a gas jar.",
  },
  {
    id: "ethylene-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Ethylene gasbag",
    symbol: "C2H4",
    formula: "C2H4",
    state: "gas",
    accent: "#cbd5e1",
    description: "Ethylene gas stored in a gasbag.",
  },
  {
    id: "gas-mixture-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Gas mixture gasbag",
    symbol: "Gas mixture",
    formula: "Gas mixture",
    state: "gas",
    accent: "#cbd5e1",
    description: "Gas mixture stored in a gasbag.",
  },
  {
    id: "hydrogen-bromide",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen bromide",
    symbol: "HBr",
    formula: "HBr",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen bromide gas in a gas jar.",
  },
  {
    id: "hydrogen-bromide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen bromide gasbag",
    symbol: "HBr",
    formula: "HBr",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen bromide gas stored in a gasbag.",
  },
  {
    id: "hydrogen-iodide",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen iodide",
    symbol: "HI",
    formula: "HI",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen iodide gas in a gas jar.",
  },
  {
    id: "hydrogen-iodide-gasbag",
    module: "inorganic",
    category: "gases",
    name: "Hydrogen iodide gasbag",
    symbol: "HI",
    formula: "HI",
    state: "gas",
    accent: "#cbd5e1",
    description: "Hydrogen iodide gas stored in a gasbag.",
  },
  {
    id: "match",
    module: "inorganic",
    category: "equipment",
    name: "Match",
    symbol: "MTH",
    state: "device",
    accent: "#f8eed3",
    description: "Single matchstick for ignition.",
    hidden: true, // Custom flag to hide from sidebar if we want
  },
  {
    id: "sandpaper",
    module: "inorganic",
    category: "equipment",
    name: "Sandpaper",
    symbol: "SND",
    state: "device",
    accent: "#F4D8B8",
    description: "Used to clean or polish surfaces.",
  },
  {
    id: "copper-wire",
    module: "inorganic",
    category: "equipment",
    name: "Copper wire",
    symbol: "Cu",
    state: "solid",
    accent: "#B76E53",
    description: "A copper wire sample for reactions.",
  },
  {
    id: "wooden-box",
    module: "inorganic",
    category: "equipment",
    name: "Wooden box",
    symbol: "BOX",
    state: "device",
    accent: "#9F6636",
    description: "A wooden box.",
  },
  {
    id: "balloon",
    module: "inorganic",
    category: "equipment",
    name: "Balloon",
    symbol: "BAL",
    state: "device",
    accent: "#0098D8",
    description: "A blue balloon.",
  },
  {
    id: "towel",
    module: "inorganic",
    category: "equipment",
    name: "Towel",
    symbol: "TWL",
    state: "device",
    accent: "#FBBD00",
    description: "A cleaning towel.",
  },
  {
    id: "cotton",
    module: "inorganic",
    category: "equipment",
    name: "Cotton",
    symbol: "CTN",
    state: "device",
    accent: "#DEE0E1",
    description: "A piece of cotton.",
  },
  {
    id: "filter-paper",
    module: "inorganic",
    category: "equipment",
    name: "Filter paper",
    symbol: "FP",
    state: "device",
    accent: "#EAE8E5",
    description: "Semi-permeable paper barrier used to separate fine solids from liquids.",
  },
];

export const ORGANIC_LIBRARY: OrganicLibraryItem[] = [
  {
    id: "atom-c",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "C",
    color: "#0f172a",
    description: "Carbon backbone atom.",
  },
  {
    id: "atom-h",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "H",
    color: "#e2e8f0",
    description: "Hydrogen atom.",
  },
  {
    id: "atom-o",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "O",
    color: "#ef4444",
    description: "Oxygen hetero atom.",
  },
  {
    id: "atom-n",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "N",
    color: "#3b82f6",
    description: "Nitrogen hetero atom.",
  },
  {
    id: "atom-cl",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Cl",
    color: "#22c55e",
    description: "Chloro substituent.",
  },
  {
    id: "atom-br",
    module: "organic",
    category: "atoms",
    kind: "atom",
    label: "Br",
    color: "#f97316",
    description: "Bromo substituent.",
  },
  {
    id: "ring-benzene",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Benzene",
    template: "benzene",
    color: "#ec4899",
    description: "Drop a six-member aromatic ring.",
  },
  {
    id: "ring-cyclohexane",
    module: "organic",
    category: "rings",
    kind: "ring",
    label: "Cyclohexane",
    template: "cyclohexane",
    color: "#10b981",
    description: "Drop a six-member saturated ring.",
  },
  {
    id: "bond-single",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Single",
    order: 1,
    color: "#475569",
    description: "Create or update a single bond.",
  },
  {
    id: "bond-double",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Double",
    order: 2,
    color: "#475569",
    description: "Create or update a double bond.",
  },
  {
    id: "bond-triple",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Triple",
    order: 3,
    color: "#475569",
    description: "Create or update a triple bond.",
  },
  {
    id: "bond-aromatic",
    module: "organic",
    category: "bonds",
    kind: "bond",
    label: "Aromatic",
    order: "aromatic",
    color: "#8b5cf6",
    description: "Use for aromatic link styling.",
  },
  {
    id: "group-oh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "OH",
    color: "#ef4444",
    description: "Hydroxyl group fragment.",
  },
  {
    id: "group-cooh",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "COOH",
    color: "#f97316",
    description: "Carboxylic acid fragment.",
  },
  {
    id: "group-nh2",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "NH2",
    color: "#3b82f6",
    description: "Primary amine fragment.",
  },
  {
    id: "group-ch3",
    module: "organic",
    category: "groups",
    kind: "group",
    label: "CH3",
    color: "#0f172a",
    description: "Methyl fragment.",
  },
];

export function getCategoriesForModule(module: ChemistryModule): SidebarCategory[] {
  return module === "inorganic" ? INORGANIC_CATEGORIES : ORGANIC_CATEGORIES;
}

export function getLibraryForModule(module: ChemistryModule): ChemistryLibraryItem[] {
  return module === "inorganic" ? INORGANIC_LIBRARY : ORGANIC_LIBRARY;
}

export function getDefaultCategoryForModule(module: ChemistryModule): ChemistryCategory {
  return getCategoriesForModule(module)[0].id;
}
